/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsUsuario;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
/**
 *
 * @author VALENTINO
 */
public class DevolucionUsuario extends javax.swing.JPanel {
Connection cn; // Asumo que tienes tu lógica de conexión
DefaultTableModel modelo;
int idUsuarioLogueado; // Variable para saber de quién buscar los libros
int idUsuario;
    /**
     * Creates new form DevolucionUsuario
     */
    public DevolucionUsuario(int idUsuario) {
        initComponents();
        this.idUsuarioLogueado = idUsuario;
        configurarTabla();
        cargarMisPrestamos();
    }
    private void configurarTabla() {
        modelo = new DefaultTableModel();
        modelo.addColumn("Libro");
        modelo.addColumn("F. Préstamo");
        modelo.addColumn("F. Vencimiento");
        modelo.addColumn("Estado");
        modelo.addColumn("Multa Aprox.");
        tblMisPrestamos.setModel(modelo);
    }
    // --- METODO 1: Cargar TODOS los préstamos pendientes del usuario ---
    public void cargarMisPrestamos() {
        String sql = "SELECT p.idprestamo, l.titulo, p.fechadevolucionestimada, p.fechaprestamo " +
                     "FROM PRESTAMO p " +
                     "INNER JOIN DETALLE_PRESTAMO dp ON p.idprestamo = dp.idprestamo " +
                     "INNER JOIN EJEMPLAR e ON dp.idejemplar = e.idejemplar " +
                     "INNER JOIN LIBROS l ON e.idlibro = l.idlibro " +
                     "WHERE p.idusuariolector = ? AND p.estado = TRUE";

        procesarConsulta(sql, null); // null indica que no hay filtro de fecha extra
    }
    // --- LÓGICA COMÚN PARA LLENAR LA TABLA ---
    private void procesarConsulta(String sql, String fechaFiltro) {
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setInt(1, idUsuarioLogueado);
            
            if (fechaFiltro != null) {
                pst.setDate(2, java.sql.Date.valueOf(fechaFiltro));
            }

            ResultSet rs = pst.executeQuery();
            modelo.setRowCount(0);
            LocalDate hoy = LocalDate.now();

            while (rs.next()) {
                Date fechaVenceSQL = rs.getDate("fechadevolucionestimada");
                LocalDate fechaVence = fechaVenceSQL.toLocalDate();
                
                // Calcular diferencia de días
                long diasRetraso = ChronoUnit.DAYS.between(fechaVence, hoy);
                
                String estado = "A tiempo";
                double multa = 0.0;
                
                if (diasRetraso > 0) {
                    estado = "CON RETRASO (" + diasRetraso + " días)";
                    multa = diasRetraso * 5.00; // 5 soles por día de mora
                } else {
                    // Opcional: Mostrar cuántos días faltan para devolver
                    long diasRestantes = ChronoUnit.DAYS.between(hoy, fechaVence);
                    estado = "Vence en " + diasRestantes + " días";
                }

                modelo.addRow(new Object[]{
                    rs.getInt("idprestamo"),
                    rs.getString("titulo"),
                    rs.getDate("fechaprestamo"),
                    fechaVenceSQL,
                    estado,
                    String.format("S/. %.2f", multa)
                });
            }
            
            if(modelo.getRowCount() == 0 && fechaFiltro != null) {
                 JOptionPane.showMessageDialog(this, "No encontré préstamos en esa fecha.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al consultar: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMisPrestamos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaBusqueda = new javax.swing.JTextField();
        btnDevolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        tblMisPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMisPrestamos);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Devolución de Libro");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Fecha para buscar Devolucion:");

        btnDevolver.setBackground(new java.awt.Color(24, 118, 210));
        btnDevolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDevolver.setForeground(new java.awt.Color(255, 255, 255));
        btnDevolver.setText("Ver Libros Devueltos");
        btnDevolver.setBorder(null);
        btnDevolver.setBorderPainted(false);
        btnDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDevolverMouseClicked(evt);
            }
        });
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/descarga (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtFechaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtFechaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolverMouseClicked

    }//GEN-LAST:event_btnDevolverMouseClicked

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        String fecha = txtFechaBusqueda.getText();

        // SQL filtra por Usuario (logueado) Y por Fecha de Préstamo
        String sql = "SELECT p.idprestamo, l.titulo, p.fechadevolucionestimada, p.fechaprestamo " +
        "FROM PRESTAMO p " +
        "INNER JOIN DETALLE_PRESTAMO dp ON p.idprestamo = dp.idprestamo " +
        "INNER JOIN EJEMPLAR e ON dp.idejemplar = e.idejemplar " +
        "INNER JOIN LIBROS l ON e.idlibro = l.idlibro " +
        "WHERE p.idusuariolector = ? AND p.estado = TRUE AND p.fechaprestamo = ?";

        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setInt(1, idUsuarioLogueado); // Variable global del ID del usuario
            pst.setDate(2, java.sql.Date.valueOf(fecha)); // La fecha ingresada

            ResultSet rs = pst.executeQuery();
            modelo.setRowCount(0); // Limpiar tabla

            while (rs.next()) {
                // ... lógica para llenar la fila (igual que antes) ...
                modelo.addRow(new Object[]{
                    rs.getString("titulo"),
                    rs.getDate("fechaprestamo"),
                    rs.getDate("fechadevolucionestimada"),
                    "Pendiente"
                });
            }

            if(modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No tienes préstamos activos de esa fecha.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Verifique la fecha (YYYY-MM-DD) o conexión.");
        }
    }//GEN-LAST:event_btnDevolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMisPrestamos;
    private javax.swing.JTextField txtFechaBusqueda;
    // End of variables declaration//GEN-END:variables
}
