/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsUsuario;
import capaDatos.clsJDBC;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author VALENTINO
 */
public class Reporte07 extends javax.swing.JPanel {
clsJDBC jdbc = new clsJDBC();
    /**
     * Creates new form Reporte07
     */
    public Reporte07() {
        initComponents();
        cargarAutores(); // <--- LLAMAMOS AL MÉTODO PARA LLENAR EL COMBO
    }
   private void cargarAutores() {
        // CORRECCIÓN AQUÍ: Cambiamos 'names' por 'nombres'
        String sql = "SELECT nombres || ' ' || apepaterno || ' ' || apematerno AS nombre_completo " +
                     "FROM AUTOR WHERE estado = TRUE ORDER BY nombres ASC"; 

        try {
            cbxAutor.removeAllItems();
            cbxAutor.addItem("-- Seleccione un Autor --");

            ResultSet rs = jdbc.consultarBD(sql);
            
            while (rs.next()) {
                cbxAutor.addItem(rs.getString("nombre_completo"));
            }
            
            jdbc.desconectar();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar autores: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaReporte = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        cbxAutor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Autor:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscarMarca.png"))); // NOI18N
        jButton1.setText("Búscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        vistaReporte.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vistaReporte.setLayer(cbxAutor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vistaReporte.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout vistaReporteLayout = new javax.swing.GroupLayout(vistaReporte);
        vistaReporte.setLayout(vistaReporteLayout);
        vistaReporteLayout.setHorizontalGroup(
            vistaReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaReporteLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton1)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        vistaReporteLayout.setVerticalGroup(
            vistaReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaReporteLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(vistaReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(422, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaReporte)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaReporte)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Validar selección
        if (cbxAutor.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un autor de la lista.");
            return;
        }

        // 2. Obtener el nombre seleccionado
        String autorSeleccionado = cbxAutor.getSelectedItem().toString();

        Connection cn = null;
        try {
            // 3. Obtener conexión
            cn = jdbc.conectar();

            // 4. Preparar el Parámetro (Map)
            // "p_nombreAutor" debe ser IDÉNTICO al nombre del parámetro en iReport
            Map<String, Object> parametros = new HashMap<>();
            parametros.put("p_nombreAutor", autorSeleccionado);

            // 5. Cargar el reporte (Asegúrate de la ruta correcta)
            // Si el .jasper está en el paquete 'reportes' dentro de 'src':
            java.net.URL rutaReporte = getClass().getResource("/reportes/reporte7.jasper");
            
            if (rutaReporte == null) {
                JOptionPane.showMessageDialog(this, "No se encuentra el archivo .jasper en /reportes/");
                return;
            }

            // 6. Llenar el reporte
            JasperReport reporte = (JasperReport) JRLoader.loadObject(rutaReporte);
            JasperPrint print = JasperFillManager.fillReport(reporte, parametros, cn);

            // 7. Mostrar el visor
            JasperViewer visor = new JasperViewer(print, false); // false para que no cierre todo el sistema al salir
            visor.setTitle("Reporte de Libros por Autor");
            visor.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar reporte: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // Opcional: jdbc.desconectar(); si tu clase lo requiere, 
            // aunque Jasper suele gestionar la conexión de lectura bien.
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxAutor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JDesktopPane vistaReporte;
    // End of variables declaration//GEN-END:variables
}
