/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsUsuario;

import capaDatos.clsJDBC;
import capaLogica.Libro;
import capaLogica.Reportes;
import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.DefaultComboBoxModel;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.swing.JRViewer;
import org.apache.commons.jocl.JOCLContentHandler;

/**
 *
 * @author LENOVO
 */
public class Reporte14 extends javax.swing.JPanel {

    Libro li = new Libro();

    public Reporte14() {
        initComponents();
        CargarTitulos();
    }

    private void CargarTitulos() {
        try {
            DefaultComboBoxModel cbo = new DefaultComboBoxModel();
            ResultSet rs = li.listarTitulosLibros();

            while (rs.next()) {
                String titu = rs.getString("titulo");
                cbo.addElement(titu);
            }

            cboTitulos.setModel(cbo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los titulos de los libros: " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JDesktopPane();
        cboTitulos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnMostrarReporte = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Escoga el titulo del libro");

        btnMostrarReporte.setText("BUSCAR ESTADO EJEMPLARES");
        btnMostrarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarReporteActionPerformed(evt);
            }
        });

        contenedor.setLayer(cboTitulos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        contenedor.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        contenedor.setLayer(btnMostrarReporte, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(cboTitulos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnMostrarReporte)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTitulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnMostrarReporte))
                .addContainerGap(441, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarReporteActionPerformed
        try {

            if (cboTitulos.getSelectedItem() == null
                    || cboTitulos.getSelectedItem().toString().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Escoja el título de un libro");
                return;
            }

            String titulo = cboTitulos.getSelectedItem().toString();

            this.contenedor.setLayout(new BorderLayout());
            this.contenedor.removeAll();

            Map<String, Object> parametros = new HashMap<>();
            parametros.put("titulo", titulo);

            JRViewer objReporte = new Reportes().reporteInterno("rp_tocto_14.jasper", parametros);

            this.contenedor.add(objReporte);
            this.contenedor.revalidate();
            this.contenedor.repaint();
            objReporte.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "ERROR en Reporte: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMostrarReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarReporte;
    private javax.swing.JComboBox<String> cboTitulos;
    private javax.swing.JDesktopPane contenedor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
