/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;

import capaLogica.Categoria;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JFrame;

/**
 *
 * @author Percy Alexander
 */
public class BuscarCategoria extends javax.swing.JPanel {

    Categoria objCategoria = new Categoria();
    private ManLibro panelPrincipal;
    private JFrame frameContenedor;

    /**
     * Creates new form BuscarCategoria
     */
    public BuscarCategoria(ManLibro principal, JFrame contenedor) {
        initComponents();
        this.panelPrincipal = principal;
        this.frameContenedor = contenedor;
        listarCategorias();
    }

    private void listarCategorias() {
        ResultSet rsCategorias = null;
        DefaultTableModel modelo = new DefaultTableModel();

        // Definición de las columnas de la tabla
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("DESCRIPCIÓN");
        modelo.addColumn("ESTADO");

        try {
            // 1. Obtener los valores de los filtros
            String nombre = txtNombre.getText();
            String descripcion = txtDescripcion.getText();
            // String estadoSeleccionado = cbxEstado.getSelectedItem().toString(); // ❌ ELIMINADO

            // 💡 REEMPLAZO: Establecer "Todos" como filtro fijo
            String estadoSeleccionado = "Todos";

            // 2. Llamar al nuevo método de filtrado
            String filtroEstado = estadoSeleccionado;

            // ❌ Lógica de conversión de estado eliminada
            /*
            if (estadoSeleccionado.equalsIgnoreCase("Activo")) {
                filtroEstado = "Activo"; // Corresponderá a TRUE en la lógica
            } else if (estadoSeleccionado.equalsIgnoreCase("Inactivo")) {
                filtroEstado = "Inactivo"; // Corresponderá a FALSE en la lógica
            } else {
                filtroEstado = "Todos";
            }
             */
            rsCategorias = objCategoria.filtrarCategorias(nombre, descripcion, filtroEstado);

            // 3. Llenar la tabla con los resultados
            while (rsCategorias.next()) {
                modelo.addRow(new Object[]{
                    rsCategorias.getInt("idcategoria"),
                    rsCategorias.getString("nombrecategoria"),
                    rsCategorias.getString("descripcion"),
                    rsCategorias.getBoolean("estado") ? "Activo" : "Inactivo"
                });
            }

            // 4. Asignar el modelo a la JTable y actualizar el contador
            tblListadoCategorias.setModel(modelo);
            txtTotalCategorias.setText(String.valueOf(tblListadoCategorias.getRowCount()));

            // 5. Cerrar el ResultSet (importante para evitar fugas de conexión)
            rsCategorias.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al listar categorías: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoCategorias = new javax.swing.JTable();
        txtTotalCategorias = new javax.swing.JLabel();
        txtTotalCategorias1 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyReleased(evt);
            }
        });

        tblListadoCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListadoCategorias);

        txtTotalCategorias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotalCategorias.setText("jLabel1");

        txtTotalCategorias1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotalCategorias1.setText("Total:");

        btnSeleccionar.setBackground(new java.awt.Color(24, 118, 210));
        btnSeleccionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setBorder(null);
        btnSeleccionar.setBorderPainted(false);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Descripción:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(txtTotalCategorias1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTotalCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCategorias)
                    .addComponent(txtTotalCategorias1))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        listarCategorias();
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyReleased
        listarCategorias();
    }//GEN-LAST:event_txtDescripcionKeyReleased

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int fila = tblListadoCategorias.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Categoría de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            String estadoCategoria = tblListadoCategorias.getValueAt(fila, 3).toString();

            if (!estadoCategoria.equalsIgnoreCase("Activo")) {
                JOptionPane.showMessageDialog(this,
                        "Solo se pueden seleccionar Categorías Activas (Estado: " + estadoCategoria + ").",
                        "Categoría Inactiva",
                        JOptionPane.WARNING_MESSAGE);
                return; // 🛑 DETIENE la ejecución si no está Activo.
            }

            // 2. Obtener los datos (Solo se ejecuta si el estado es Activo)
            String idString = tblListadoCategorias.getValueAt(fila, 0).toString();
            Integer idCategoria = Integer.parseInt(idString); // Columna 0: ID
            String nombreCategoria = tblListadoCategorias.getValueAt(fila, 1).toString(); // Columna 1: NOMBRE

            // 3. Llamar al método delegado del panel principal
            if (panelPrincipal != null) {
                panelPrincipal.setCategoriaSeleccionada(idCategoria, nombreCategoria);

                // 4. Cerrar el JFrame contenedor
                if (frameContenedor != null) {
                    frameContenedor.dispose();
                }
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,
                    "Error de formato de ID. El código no es un número válido: " + nfe.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al seleccionar la categoría: " + e.getMessage(),
                    "Error General", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListadoCategorias;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtTotalCategorias;
    private javax.swing.JLabel txtTotalCategorias1;
    // End of variables declaration//GEN-END:variables
}
