/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;

import capaLogica.Editorial;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ItemEvent;
import java.awt.event.ActionEvent;

/**
 *
 * @author Percy Alexander
 */
public class BuscarEditorial extends javax.swing.JPanel {

    Editorial objEditorial = new Editorial();

    // Referencias para la comunicación con el panel principal
    private ManLibro panelPrincipal;
    private JFrame frameContenedor;

    /**
     * Creates new form BuscarEditorial
     */
    public BuscarEditorial(ManLibro principal, JFrame contenedor) {
        initComponents();
        this.panelPrincipal = principal;
        this.frameContenedor = contenedor;

        // Inicialización y listado
        llenarEstado();
        listarEditoriales();
    }

    private void llenarEstado() {
        // Rellena el JComboBox cbxEstado
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        modelo.addElement("Todos");
        modelo.addElement("Activo");
        modelo.addElement("Inactivo");
        cbxEstado.setModel(modelo);
        cbxEstado.setSelectedIndex(0);
    }

    private void listarEditoriales() {
        ResultSet rsEditoriales = null;
        DefaultTableModel modelo = new DefaultTableModel();

        // Las columnas del JTable siguen mostrando todos los campos
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("TELÉFONO");
        modelo.addColumn("CORREO");
        modelo.addColumn("ESTADO");

        try {
            // 1. Obtener los valores de los filtros
            String nombre = txtNombre.getText();
            String telefono = txtTelefono.getText();
            // String correo = txtCorreo.getText(); // Se elimina la obtención de este campo
            String estadoSeleccionado = cbxEstado.getSelectedItem().toString();

            // 2. Llamar al método de filtrado con solo TRES argumentos
            rsEditoriales = objEditorial.filtrarEditoriales(nombre, telefono, estadoSeleccionado);

            // 3. Llenar la tabla (usando los 5 campos de la BD)
            while (rsEditoriales.next()) {
                modelo.addRow(new Object[]{
                    rsEditoriales.getInt("ideditorial"),
                    rsEditoriales.getString("nombre"),
                    rsEditoriales.getString("telefono"),
                    rsEditoriales.getString("correo"), // Se sigue leyendo para mostrar
                    rsEditoriales.getBoolean("estado") ? "Activo" : "Inactivo"
                });
            }

            tblListadoEditoriales.setModel(modelo);
            txtTotalEditoriales.setText(String.valueOf(tblListadoEditoriales.getRowCount()));
            rsEditoriales.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al listar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cbxEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoEditoriales = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotalEditoriales = new javax.swing.JLabel();

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });

        cbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoActionPerformed(evt);
            }
        });

        tblListadoEditoriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListadoEditoriales);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jLabel1.setText("Total");

        txtTotalEditoriales.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalEditoriales))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSeleccionar))
                                .addGap(32, 32, 32)
                                .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSeleccionar)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotalEditoriales))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        listarEditoriales();
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        listarEditoriales();
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        listarEditoriales();
    }//GEN-LAST:event_cbxEstadoActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int fila = tblListadoEditoriales.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Editorial de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 1. OBTENER Y VALIDAR EL ESTADO DE VIGENCIA (Índice 4: columna 'estado')
            String estadoEditorial = tblListadoEditoriales.getValueAt(fila, 4).toString();

            if (!estadoEditorial.equalsIgnoreCase("Activo")) {
                JOptionPane.showMessageDialog(this,
                        "Solo se pueden seleccionar Editoriales Activas (Estado: " + estadoEditorial + ").",
                        "Editorial Inactiva",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 2. Obtener los datos (Solo se ejecuta si el estado es "Si")
            String idString = tblListadoEditoriales.getValueAt(fila, 0).toString(); // Columna 0: ID
            Integer idEditorial = Integer.parseInt(idString);
            String nombreEditorial = tblListadoEditoriales.getValueAt(fila, 1).toString(); // Columna 1: NOMBRE

            // 3. Llamar al método delegado del panel principal
            if (panelPrincipal != null) {
                panelPrincipal.setEditorialSeleccionada(idEditorial, nombreEditorial);

                // 4. Cerrar el JFrame contenedor
                if (frameContenedor != null) {
                    frameContenedor.dispose();
                }
            }

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,
                    "Error de formato de ID. El código no es un número válido: " + nfe.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al seleccionar la Editorial: " + e.getMessage(),
                    "Error General", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListadoEditoriales;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JLabel txtTotalEditoriales;
    // End of variables declaration//GEN-END:variables
}
