/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;

import capaLogica.Autor; // Asegúrate de que esta clase exista
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JFrame;
import java.sql.SQLException;

/**
 *
 * @author Percy Alexander
 */
public class BuscarAutor extends javax.swing.JPanel {

    private ManAsignarAutorLibro panelAsignarLibro; // Referencia al delegado
    private javax.swing.JDialog dialogoContenedor;
    Autor objAutor = new Autor();

    /**
     * Creates new form BuscarAutor
     */
    public BuscarAutor(ManAsignarAutorLibro principal, javax.swing.JDialog contenedor) {
        initComponents();
        this.panelAsignarLibro = principal; // Guarda la referencia del JDialog
        this.dialogoContenedor = contenedor;
        listarAutores();
    }

    private void listarAutores() {
        ResultSet rsAutores = null;

        DefaultTableModel modelo = new DefaultTableModel();

        // Definición de las columnas de la tabla (6 columnas)
        modelo.addColumn("ID");

        modelo.addColumn("NOMBRES");

        modelo.addColumn("AP. PATERNO");

        modelo.addColumn("AP. MATERNO");

        modelo.addColumn("DESCRIPCIÓN");

        modelo.addColumn("ESTADO"); // Índice 5

        try {

            // 1. Obtener los valores de los filtros
            String nombre = txtNombre.getText();

            // String estadoSeleccionado = cboEstado.getSelectedItem().toString(); // ❌ ELIMINADO
            String filtroEstado = "Todos"; // Valor fijo después de eliminar el JComboBox

            // 3. Llamar al método de filtrado 
            // NOTA: Asegúrate de que Autor.filtrarAutores pueda manejar 'filtroEstado' como "Todos"
            rsAutores = objAutor.filtrarAutores(nombre, filtroEstado);

            // 4. Llenar la tabla con los resultados
            while (rsAutores.next()) {

                modelo.addRow(new Object[]{
                    rsAutores.getInt("idautor"),
                    rsAutores.getString("nombres"),
                    rsAutores.getString("apepaterno"),
                    rsAutores.getString("apematerno"),
                    rsAutores.getString("descripcion"),
                    rsAutores.getBoolean("estado") ? "Activo" : "Inactivo" // Columna 5: ESTADO
                });

            }

            // 5. Asignar el modelo a la JTable y actualizar el contador
            tblListadoAutores.setModel(modelo);

            txtTotalAutores.setText(String.valueOf(tblListadoAutores.getRowCount()));

            // 6. Cerrar el ResultSet 
            rsAutores.close();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this, "Error de base de datos al listar autores: " + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);

        } catch (Exception e) {

            // Manejo de otras excepciones (NullPointerException, etc.)
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoAutores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTotalAutores = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        tblListadoAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListadoAutores);

        jLabel1.setText("Total");

        txtTotalAutores.setText("Total");

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(txtTotalAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotalAutores))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int fila = tblListadoAutores.getSelectedRow();

        if (fila == -1) {

            JOptionPane.showMessageDialog(this, "Debe seleccionar un Autor de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);

            return;

        }

        try {

            // 1. VALIDACIÓN: Obtener y verificar el ESTADO (Índice 5)
            // Columna 5 es el ESTADO, según tu método listarAutores()
            String estadoAutor = tblListadoAutores.getValueAt(fila, 5).toString();

            // 🛑 Lógica de Bloqueo 🛑
            if (!estadoAutor.equalsIgnoreCase("Activo")) {

                JOptionPane.showMessageDialog(this,
                        "Solo se pueden seleccionar Autores Activos (Estado: " + estadoAutor + ").",
                        "Autor Inactivo",
                        JOptionPane.WARNING_MESSAGE);

                return; // 🛑 ESTA LÍNEA ES CRUCIAL: Detiene la ejecución aquí.

            }

            // 2. Obtener los datos (Solo se ejecuta si el estado es Activo)
            String idString = tblListadoAutores.getValueAt(fila, 0).toString();

            Integer idAutor = Integer.parseInt(idString);

            // ... (obtención de nombres, etc.) ...
            String nombres = tblListadoAutores.getValueAt(fila, 1).toString();

            String apePaterno = tblListadoAutores.getValueAt(fila, 2).toString();

            String apeMaterno = tblListadoAutores.getValueAt(fila, 3).toString();

            String nombreCompleto = nombres + " " + apePaterno + " " + apeMaterno;

            // 3. Llamar al método delegado del panel principal (ManAsignarAutorLibro)
            if (panelAsignarLibro != null) {

                panelAsignarLibro.setAutorSeleccionado(idAutor, nombreCompleto.trim());

                // 4. Cerrar el JFrame contenedor
                if (dialogoContenedor != null) {

                    dialogoContenedor.dispose();

                }

            }

        } catch (NumberFormatException nfe) {

            JOptionPane.showMessageDialog(this, "Error de formato de número al seleccionar el ID: " + nfe.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Error al seleccionar el autor: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        listarAutores();
    }//GEN-LAST:event_txtNombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListadoAutores;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtTotalAutores;
    // End of variables declaration//GEN-END:variables
}
