/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;

import capaDatos.clsJDBC;
import capaLogica.DevolucionClase;
import capaLogica.Usuarios;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author VALENTINO
 */
public class Devolucion extends javax.swing.JPanel {

    clsJDBC jdbc = new clsJDBC();
    DefaultTableModel modelo;

    /**
     * Creates new form Devolucion
     */
    public Devolucion() {
        initComponents();
        configurarTabla();

    }

    private void configurarTabla() {
        modelo = new DefaultTableModel();

        modelo.addColumn("ID Ejemplar");
        modelo.addColumn("Título");
        modelo.addColumn("Observaciones");
        modelo.addColumn("Estado actual");
        modelo.addColumn("Observacion Devolucion");
        modelo.addColumn("Multa");

        tblDevolucion.setModel(modelo);
    }

    private void cargarEjemplaresPrestamo(int idPrestamo) {
        try {
            modelo.setRowCount(0);

            clsJDBC db = new clsJDBC();
            db.conectar();
            Connection con = db.getCon();

            String sql = """
                SELECT e.idejemplar, l.titulo, dp.observaciones, 
                       CASE WHEN e.estado_devolucion = FALSE THEN 'Pendiente'
                            ELSE 'Devuelto' END AS estado
                FROM ejemplar e
                INNER JOIN detalle_prestamo dp ON dp.idejemplar = e.idejemplar
                INNER JOIN libros l ON l.idlibro = e.idlibro
                WHERE dp.idprestamo = ? AND e.estado_devolucion = FALSE
            """;

            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, idPrestamo);

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("idejemplar"),
                    rs.getString("titulo"),
                    rs.getString("observaciones"),
                    rs.getString("estado")
                });
            }

            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Todos los ejemplares ya fueron devueltos.",
                        "Sin pendientes", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar ejemplares: " + e.getMessage(),
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarFormulario() {
        txtLector.setText("");

        DefaultTableModel modelo = (DefaultTableModel) tblDevolucion.getModel();
        modelo.setRowCount(0);

        jdFecha.setDate(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtLector = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarPrestamo1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDevolucion = new javax.swing.JTable();
        btnGrabarDevolucion = new javax.swing.JButton();
        jdFecha = new com.toedter.calendar.JDateChooser();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Fecha del préstamo:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Lector:");

        btnBuscarPrestamo1.setBackground(new java.awt.Color(24, 118, 210));
        btnBuscarPrestamo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarPrestamo1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPrestamo1.setText("Búscar préstamo");
        btnBuscarPrestamo1.setBorder(null);
        btnBuscarPrestamo1.setBorderPainted(false);
        btnBuscarPrestamo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPrestamo1MouseClicked(evt);
            }
        });
        btnBuscarPrestamo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestamo1ActionPerformed(evt);
            }
        });

        tblDevolucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDevolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDevolucionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDevolucion);

        btnGrabarDevolucion.setBackground(new java.awt.Color(24, 118, 210));
        btnGrabarDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGrabarDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnGrabarDevolucion.setText("Registrar Devolución");
        btnGrabarDevolucion.setBorder(null);
        btnGrabarDevolucion.setBorderPainted(false);
        btnGrabarDevolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGrabarDevolucionMouseClicked(evt);
            }
        });
        btnGrabarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarDevolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(btnGrabarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLector, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(txtLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnBuscarPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnGrabarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPrestamo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPrestamo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPrestamo1MouseClicked

    private void btnBuscarPrestamo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamo1ActionPerformed
        try {
            if (txtLector.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese nombre del lector.");
                return;
            }

            Usuarios u = new Usuarios();
            int idLector = u.obtenerIdLectorPorNombreCompleto(txtLector.getText());

            if (idLector == 0) {
                JOptionPane.showMessageDialog(this, "Lector no encontrado.");
                return;
            }

            clsJDBC db = new clsJDBC();
            db.conectar();
            Connection con = db.getCon();

            String sql = "SELECT idprestamo FROM prestamo WHERE idusuariolector = ? AND estado='activo'";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, idLector);
            ResultSet rs = pst.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this,
                        "El lector no tiene préstamos activos.");
                return;
            }

            int idPrestamo = rs.getInt(1);
            cargarEjemplaresPrestamo(idPrestamo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarPrestamo1ActionPerformed

    private void btnGrabarDevolucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrabarDevolucionMouseClicked

    }//GEN-LAST:event_btnGrabarDevolucionMouseClicked

    private void btnGrabarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarDevolucionActionPerformed
        try {
            if (txtLector.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese lector.");
                return;
            }

            if (jdFecha.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Seleccione fecha real.");
                return;
            }

            if (tblDevolucion.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No hay ejemplares a devolver.");
                return;
            }

            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String fechaReal = df.format(jdFecha.getDate());

            // --- EJECUTAR DEVOLUCIÓN ---
            DevolucionClase d = new DevolucionClase();

            boolean ok = d.registrarDevolucion(
                    txtLector.getText(),
                    fechaReal,
                    modelo
            );

            if (ok) {
                JOptionPane.showMessageDialog(this,
                        "Devolución registrada correctamente.");
                modelo.setRowCount(0);
                txtLector.setText("");
             
                jdFecha.setDate(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "ERROR: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGrabarDevolucionActionPerformed

    private void tblDevolucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDevolucionMouseClicked
        int fila = tblDevolucion.getSelectedRow();
        if (fila < 0) {
            return;
        }

        // 1. Preguntar si quiere multa
        String multaStr = JOptionPane.showInputDialog(
                this,
                "¿Monto de multa para este ejemplar? (0 si no hay multa)",
                "Registrar Multa",
                JOptionPane.QUESTION_MESSAGE
        );

        if (multaStr == null || multaStr.trim().isEmpty()) {
            multaStr = "0";
        }

        double multa = 0;
        try {
            multa = Double.parseDouble(multaStr);
        } catch (Exception e) {
            multa = 0;
        }

        // 2. Pedir observación
        String obs = JOptionPane.showInputDialog(
                this,
                "Ingrese observación:",
                "Observación",
                JOptionPane.QUESTION_MESSAGE
        );

        if (obs == null || obs.trim().isEmpty()) {
            obs = "Todo bien";
        }

        // Guardar en la tabla
        tblDevolucion.setValueAt(obs, fila, 4);
        tblDevolucion.setValueAt(String.valueOf(multa), fila, 5);

    }//GEN-LAST:event_tblDevolucionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPrestamo1;
    private javax.swing.JButton btnGrabarDevolucion;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdFecha;
    private javax.swing.JTable tblDevolucion;
    private javax.swing.JTextField txtLector;
    // End of variables declaration//GEN-END:variables
}
