/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;
import capaDatos.clsJDBC; 
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
/**
 *
 * @author VALENTINO
 */
public class Devolucion extends javax.swing.JPanel {
clsJDBC jdbc = new clsJDBC();
DefaultTableModel modelo;
    /**
     * Creates new form Devolucion
     */
    public Devolucion() {
        initComponents();
        configurarTabla();
        
        // Bloqueamos edición de campos informativos
        if(txtMulta != null) txtMulta.setEditable(false);
        // El txtLector ya no es tan útil como campo único porque pueden salir varios lectores,
        // pero lo dejamos por si quieres mostrar mensajes o el primero de la lista.
        if(txtLector != null) txtLector.setEditable(false);
    }
private void configurarTabla() {
        modelo = new DefaultTableModel();
        // OJO: Agregamos columnas ID PRESTAMO y LECTOR para diferenciar
        modelo.addColumn("ID Préstamo"); // Col 0
        modelo.addColumn("Lector");      // Col 1
        modelo.addColumn("ID Ejemplar"); // Col 2
        modelo.addColumn("Título");      // Col 3
        modelo.addColumn("F. Vencim.");  // Col 4
        modelo.addColumn("Días Retr.");  // Col 5
        modelo.addColumn("Estado");      // Col 6 (Editable: Bueno/Dañado)
        modelo.addColumn("Multa");       // Col 7
        tblDetalle.setModel(modelo);
        
        // Ocultar la columna ID Préstamo si quieres que se vea más limpio (Opcional)
        // tblDetalle.getColumnModel().getColumn(0).setMinWidth(0);
        // tblDetalle.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFechaPrestamo = new javax.swing.JTextField();
        txtLector = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarPrestamo1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        txtMulta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnGrabarDevolucion = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("DEVOLUCIONES");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Fecha del préstamo:");

        txtLector.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Lector:");

        btnBuscarPrestamo1.setBackground(new java.awt.Color(24, 118, 210));
        btnBuscarPrestamo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarPrestamo1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPrestamo1.setText("Búscar préstamo");
        btnBuscarPrestamo1.setBorder(null);
        btnBuscarPrestamo1.setBorderPainted(false);
        btnBuscarPrestamo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPrestamo1MouseClicked(evt);
            }
        });
        btnBuscarPrestamo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestamo1ActionPerformed(evt);
            }
        });

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalle);

        txtMulta.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Multa:");

        btnGrabarDevolucion.setBackground(new java.awt.Color(24, 118, 210));
        btnGrabarDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGrabarDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnGrabarDevolucion.setText("Registrar Devolución");
        btnGrabarDevolucion.setBorder(null);
        btnGrabarDevolucion.setBorderPainted(false);
        btnGrabarDevolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGrabarDevolucionMouseClicked(evt);
            }
        });
        btnGrabarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarDevolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLector, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btnGrabarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(btnBuscarPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrabarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPrestamo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPrestamo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPrestamo1MouseClicked

    private void btnBuscarPrestamo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamo1ActionPerformed
       String fecha = txtFechaPrestamo.getText(); // Asegúrate que tu campo se llama así o txtIdPrestamo
        
        // Validación básica de formato fecha
        if (!fecha.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Ingrese fecha válida (YYYY-MM-DD). Ejemplo: 2025-05-01");
            return;
        }

        // QUERY MODIFICADA: Busca por fechaprestamo
        String sql = "SELECT p.idprestamo, u.nombre || ' ' || u.ap_paterno AS lector, " +
                     "p.fechadevolucionestimada, dp.idejemplar, l.titulo " +
                     "FROM PRESTAMO p " +
                     "INNER JOIN USUARIO u ON p.idusuariolector = u.idusuario " +
                     "INNER JOIN DETALLE_PRESTAMO dp ON p.idprestamo = dp.idprestamo " +
                     "INNER JOIN EJEMPLAR e ON dp.idejemplar = e.idejemplar " +
                     "INNER JOIN LIBROS l ON e.idlibro = l.idlibro " +
                     "WHERE p.fechaprestamo = '" + fecha + "' AND p.estado = 'activo'";

        try {
            ResultSet rs = jdbc.consultarBD(sql);

            modelo.setRowCount(0);
            txtMulta.setText("0.00");
            if(txtLector != null) txtLector.setText(""); 
            
            LocalDate hoy = LocalDate.now();
            boolean encontrado = false;
            double sumaTotalMulta = 0.0;

            while (rs.next()) {
                encontrado = true;
                
                // Si hay resultados, ponemos el primer lector en el campo texto (visual)
                // aunque en la tabla saldrán todos.
                if(txtLector != null && txtLector.getText().isEmpty()){
                    txtLector.setText(rs.getString("lector"));
                }

                LocalDate fechaVence = rs.getDate("fechadevolucionestimada").toLocalDate();
                long dias = ChronoUnit.DAYS.between(fechaVence, hoy);
                if (dias < 0) dias = 0;

                double multaIndividual = dias * 2.00; // Regla: 2 soles por día
                sumaTotalMulta += multaIndividual;

                modelo.addRow(new Object[]{
                    rs.getInt("idprestamo"), // Importante para agrupar luego
                    rs.getString("lector"),
                    rs.getInt("idejemplar"),
                    rs.getString("titulo"),
                    fechaVence,
                    dias,
                    "Bueno", 
                    multaIndividual
                });
            }
            
            jdbc.desconectar();

            if (encontrado) {
                txtMulta.setText(String.format("%.2f", sumaTotalMulta));
            } else {
                JOptionPane.showMessageDialog(this, "No hay préstamos activos en esa fecha.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarPrestamo1ActionPerformed

    private void btnGrabarDevolucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrabarDevolucionMouseClicked

    }//GEN-LAST:event_btnGrabarDevolucionMouseClicked

    private void btnGrabarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarDevolucionActionPerformed
        if (modelo.getRowCount() == 0) return;

        Connection cn = null;

        try {
            cn = jdbc.conectar();
            cn.setAutoCommit(false); // INICIO TRANSACCIÓN

            Statement st = cn.createStatement();
            
            // MAPA para controlar duplicados: ID_Prestamo -> ID_Devolucion
            // Esto evita que si hay 3 libros del mismo préstamo, intentemos crear 3 devoluciones.
            Map<Integer, Integer> mapaPrestamoDevolucion = new HashMap<>();

            // Preparamos las sentencias SQL (se reutilizan en el bucle)
            String sqlDev = "INSERT INTO DEVOLUCION (iddevolucion, idprestamo, fechadevolucionreal) VALUES (?, ?, ?)";
            PreparedStatement pstDev = cn.prepareStatement(sqlDev);

            String sqlDet = "INSERT INTO DETALLE_DEVOLUCION (iddetalledev, iddevolucion, idejemplar, estado, multa, observaciones) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pstDet = cn.prepareStatement(sqlDet);

            String sqlUpdEj = "UPDATE EJEMPLAR SET Estado_Devolucion = TRUE WHERE idejemplar = ?";
            PreparedStatement pstUpdEj = cn.prepareStatement(sqlUpdEj);

            // Obtener siguiente ID para Detalle (secuencial manual)
            ResultSet rsIdDet = st.executeQuery("SELECT COALESCE(MAX(iddetalledev), 0) FROM DETALLE_DEVOLUCION");
            rsIdDet.next();
            int idDetalle = rsIdDet.getInt(1) + 1;

            // --- RECORREMOS LA TABLA FILA POR FILA ---
            for (int i = 0; i < tblDetalle.getRowCount(); i++) {
                
                // Datos de la fila
                int idPrestamo = Integer.parseInt(modelo.getValueAt(i, 0).toString());
                int idEjemplar = Integer.parseInt(modelo.getValueAt(i, 2).toString());
                String estadoStr = modelo.getValueAt(i, 6).toString(); // Columna 6 es estado
                double multaItem = Double.parseDouble(modelo.getValueAt(i, 7).toString()); // Col 7 es multa

                // 1. GESTIÓN DE LA CABECERA DE DEVOLUCIÓN (Solo una por préstamo)
                int idDevolucionActual;
                
                if (mapaPrestamoDevolucion.containsKey(idPrestamo)) {
                    // Si ya creamos la cabecera en una vuelta anterior del bucle, usamos ese ID
                    idDevolucionActual = mapaPrestamoDevolucion.get(idPrestamo);
                } else {
                    // Es un préstamo nuevo en este lote: CREAMOS LA CABECERA
                    ResultSet rsIdDev = st.executeQuery("SELECT COALESCE(MAX(iddevolucion), 0) + 1 FROM DEVOLUCION");
                    rsIdDev.next();
                    idDevolucionActual = rsIdDev.getInt(1);
                    
                    pstDev.setInt(1, idDevolucionActual);
                    pstDev.setInt(2, idPrestamo);
                    pstDev.setDate(3, java.sql.Date.valueOf(LocalDate.now()));
                    pstDev.executeUpdate();
                    
                    // Guardamos en el mapa para no repetirlo
                    mapaPrestamoDevolucion.put(idPrestamo, idDevolucionActual);
                }

                // 2. INSERTAR DETALLE
                pstDet.setInt(1, idDetalle++);
                pstDet.setInt(2, idDevolucionActual);
                pstDet.setInt(3, idEjemplar);
                pstDet.setBoolean(4, estadoStr.equalsIgnoreCase("Bueno"));
                pstDet.setDouble(5, multaItem);
                pstDet.setString(6, "Estado: " + estadoStr);
                pstDet.executeUpdate();

                // 3. LIBERAR EJEMPLAR
                pstUpdEj.setInt(1, idEjemplar);
                pstUpdEj.executeUpdate();
            }

            // 4. CERRAR TODOS LOS PRÉSTAMOS INVOLUCRADOS
            // Recorremos el mapa porque ahí están los IDs únicos de préstamos procesados
            String sqlClose = "UPDATE PRESTAMO SET estado = 'completado' WHERE idprestamo = ?";
            PreparedStatement pstClose = cn.prepareStatement(sqlClose);
            
            for (Integer idPrestamoCerrar : mapaPrestamoDevolucion.keySet()) {
                pstClose.setInt(1, idPrestamoCerrar);
                pstClose.executeUpdate();
            }

            cn.commit(); // CONFIRMAR TODO
            JOptionPane.showMessageDialog(this, "Devoluciones procesadas exitosamente.");
            
            modelo.setRowCount(0);
            txtFechaPrestamo.setText("");
            txtMulta.setText("");
            if(txtLector != null) txtLector.setText("");

        } catch (Exception e) {
            try { if(cn!=null) cn.rollback(); } catch (SQLException ex) {}
            JOptionPane.showMessageDialog(this, "Error en transacción: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try { if(cn!=null) cn.close(); } catch (SQLException ex) {}
        }
    }//GEN-LAST:event_btnGrabarDevolucionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPrestamo1;
    private javax.swing.JButton btnGrabarDevolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtFechaPrestamo;
    private javax.swing.JTextField txtLector;
    private javax.swing.JTextField txtMulta;
    // End of variables declaration//GEN-END:variables
}
