/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;

import capaDatos.clsJDBC;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author VALENTINO
 */
public class Devolucion extends javax.swing.JPanel {
clsJDBC jdbc = new clsJDBC();
DefaultTableModel modelo;
    /**
     * Creates new form Devolucion
     */
    public Devolucion() {
        initComponents();
        configurarTabla();
        
    
    }
private void configurarTabla() {
        modelo = new DefaultTableModel();
        // OJO: Agregamos columnas ID PRESTAMO y LECTOR para diferenciar
        modelo.addColumn("ID Préstamo"); // Col 0
        modelo.addColumn("Lector");      // Col 1
        modelo.addColumn("ID Ejemplar"); // Col 2
        modelo.addColumn("Título");      // Col 3
        modelo.addColumn("F. Vencim.");  // Col 4
        modelo.addColumn("Días Retr.");  // Col 5
        modelo.addColumn("Estado");      // Col 6 
  
        tblDetalle.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtLector = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarPrestamo1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        txtMulta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnGrabarDevolucion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        txtFecha = new com.toedter.calendar.JDateChooser();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Fecha del préstamo:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Lector:");

        btnBuscarPrestamo1.setBackground(new java.awt.Color(24, 118, 210));
        btnBuscarPrestamo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarPrestamo1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPrestamo1.setText("Búscar préstamo");
        btnBuscarPrestamo1.setBorder(null);
        btnBuscarPrestamo1.setBorderPainted(false);
        btnBuscarPrestamo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPrestamo1MouseClicked(evt);
            }
        });
        btnBuscarPrestamo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestamo1ActionPerformed(evt);
            }
        });

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetalle);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Multa:");

        btnGrabarDevolucion.setBackground(new java.awt.Color(24, 118, 210));
        btnGrabarDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGrabarDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnGrabarDevolucion.setText("Registrar Devolución");
        btnGrabarDevolucion.setBorder(null);
        btnGrabarDevolucion.setBorderPainted(false);
        btnGrabarDevolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGrabarDevolucionMouseClicked(evt);
            }
        });
        btnGrabarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarDevolucionActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Observaciones:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane2.setViewportView(txtObservaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(281, 281, 281)
                            .addComponent(btnBuscarPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(251, 251, 251))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(85, 85, 85)
                            .addComponent(btnGrabarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLector, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(txtLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrabarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPrestamo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPrestamo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPrestamo1MouseClicked

    private void btnBuscarPrestamo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamo1ActionPerformed
       // 1. OBTENER LA FECHA DEL JDATECHOOSER
        // Asumo que tu variable del JDateChooser se llama 'txtFecha' o 'txtFechaPrestamo'
        // (Cámbialo según el nombre de variable que le pusiste en Design)
        java.util.Date fechaSeleccionada = txtFecha.getDate(); 
        
        if (fechaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una fecha válida.");
            return;
        }

        // 2. CONVERTIR A STRING (YYYY-MM-DD) PARA LA BASE DE DATOS
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fecha = sdf.format(fechaSeleccionada);

        // 3. OBTENER LECTOR (Opcional)
        String lectorBusqueda = txtLector.getText().trim();

        // 4. QUERY DINÁMICA
        String sql = "SELECT p.idprestamo, u.nombre || ' ' || u.ap_paterno AS lector, "
                + "p.fechadevolucionestimada, dp.idejemplar, l.titulo "
                + "FROM PRESTAMO p "
                + "INNER JOIN USUARIO u ON p.idusuariolector = u.idusuario "
                + "INNER JOIN DETALLE_PRESTAMO dp ON p.idprestamo = dp.idprestamo "
                + "INNER JOIN EJEMPLAR e ON dp.idejemplar = e.idejemplar "
                + "INNER JOIN LIBROS l ON e.idlibro = l.idlibro "
                + "WHERE p.fechaprestamo = '" + fecha + "' AND p.estado = 'activo'";

        // Filtro opcional por nombre de lector
        if (!lectorBusqueda.isEmpty()) {
            sql += " AND (u.nombre || ' ' || u.ap_paterno) ILIKE '%" + lectorBusqueda + "%'";
        }

        try {
            ResultSet rs = jdbc.consultarBD(sql);

            modelo.setRowCount(0);
            txtMulta.setText("");
            if(txtObservaciones != null) txtObservaciones.setText("");

            LocalDate hoy = LocalDate.now();
            boolean encontrado = false;

            while (rs.next()) {
                encontrado = true;

                LocalDate fechaVence = rs.getDate("fechadevolucionestimada").toLocalDate();
                long dias = ChronoUnit.DAYS.between(fechaVence, hoy);
                if (dias < 0) dias = 0;

                modelo.addRow(new Object[]{
                    rs.getInt("idprestamo"),
                    rs.getString("lector"),
                    rs.getInt("idejemplar"),
                    rs.getString("titulo"),
                    fechaVence,
                    dias,
                    "Bueno"
                });
            }

            jdbc.desconectar();

            if (!encontrado) {
                JOptionPane.showMessageDialog(this, "No se encontraron préstamos activos en esa fecha.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarPrestamo1ActionPerformed

    private void btnGrabarDevolucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrabarDevolucionMouseClicked

    }//GEN-LAST:event_btnGrabarDevolucionMouseClicked

    private void btnGrabarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarDevolucionActionPerformed
       // 1. VALIDACIÓN: Fila seleccionada
        int filaSeleccionada = tblDetalle.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el libro en la tabla.");
            return;
        }

        // 2. VALIDACIÓN: Multa
        String multaTexto = txtMulta.getText().trim();
        if (multaTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el monto de la multa (0 si no hay).");
            return;
        }
        
        double multaManual = 0.0;
        try {
            multaManual = Double.parseDouble(multaTexto);
            if (multaManual < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La multa debe ser un número positivo.");
            return;
        }

        // 3. CAPTURA OBSERVACIONES
        String observaciones = txtObservaciones.getText().trim();
        if (observaciones.isEmpty()) {
            observaciones = "Ninguna"; 
        }

        Connection cn = null;

        try {
            cn = jdbc.conectar();
            cn.setAutoCommit(false); 

            Statement st = cn.createStatement();

            // SQLs
            String sqlDev = "INSERT INTO DEVOLUCION (iddevolucion, idprestamo, fechadevolucionreal) VALUES (?, ?, ?)";
            PreparedStatement pstDev = cn.prepareStatement(sqlDev);

            String sqlDet = "INSERT INTO DETALLE_DEVOLUCION (iddetalledev, iddevolucion, idejemplar, estado, multa, observaciones) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pstDet = cn.prepareStatement(sqlDet);

            String sqlUpdEj = "UPDATE EJEMPLAR SET Estado_Devolucion = TRUE WHERE idejemplar = ?";
            PreparedStatement pstUpdEj = cn.prepareStatement(sqlUpdEj);

            // Datos
            int idPrestamo = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 0).toString());
            int idEjemplar = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 2).toString());
            String estadoStr = modelo.getValueAt(filaSeleccionada, 6).toString();
            
            double multaItem = multaManual; 

            // A. CABECERA
            String sqlCheck = "SELECT iddevolucion FROM DEVOLUCION WHERE idprestamo = " + idPrestamo + " AND fechadevolucionreal = CURRENT_DATE";
            ResultSet rsCheck = st.executeQuery(sqlCheck);
            
            int idDevolucionActual;
            if (rsCheck.next()) {
                idDevolucionActual = rsCheck.getInt("iddevolucion");
            } else {
                ResultSet rsIdDev = st.executeQuery("SELECT COALESCE(MAX(iddevolucion), 0) + 1 FROM DEVOLUCION");
                rsIdDev.next();
                idDevolucionActual = rsIdDev.getInt(1);
                
                pstDev.setInt(1, idDevolucionActual);
                pstDev.setInt(2, idPrestamo);
                pstDev.setDate(3, java.sql.Date.valueOf(LocalDate.now()));
                pstDev.executeUpdate();
            }
            rsCheck.close();

            // B. DETALLE
            ResultSet rsIdDet = st.executeQuery("SELECT COALESCE(MAX(iddetalledev), 0) + 1 FROM DETALLE_DEVOLUCION");
            rsIdDet.next();
            int idDetalle = rsIdDet.getInt(1);
            rsIdDet.close();

            pstDet.setInt(1, idDetalle);
            pstDet.setInt(2, idDevolucionActual);
            pstDet.setInt(3, idEjemplar);
            pstDet.setBoolean(4, estadoStr.equalsIgnoreCase("Bueno"));
            pstDet.setDouble(5, multaItem); 
            pstDet.setString(6, observaciones); 
            pstDet.executeUpdate();

            // C. LIBERAR EJEMPLAR
            pstUpdEj.setInt(1, idEjemplar);
            pstUpdEj.executeUpdate();

            // D. CERRAR PRÉSTAMO
            String sqlClose = "UPDATE PRESTAMO SET estado = 'completado' WHERE idprestamo = ?";
            PreparedStatement pstClose = cn.prepareStatement(sqlClose);
            pstClose.setInt(1, idPrestamo);
            pstClose.executeUpdate();

            cn.commit(); 
            JOptionPane.showMessageDialog(this, "Devolución registrada con éxito.");
            
            // LIMPIEZA
            modelo.removeRow(filaSeleccionada);
            txtMulta.setText(""); 
            txtObservaciones.setText("");
            
            if (modelo.getRowCount() == 0) {
                txtLector.setText("");
            }

        } catch (Exception e) {
            try { if(cn!=null) cn.rollback(); } catch (SQLException ex) {}
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try { if(cn!=null) cn.close(); } catch (SQLException ex) {}
        }
    }//GEN-LAST:event_btnGrabarDevolucionActionPerformed

    private void tblDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalleMouseClicked

       int fila = tblDetalle.getSelectedRow();
        if (fila >= 0) {
            // Actualizamos nombre lector para confirmar
            String nombreLector = tblDetalle.getValueAt(fila, 1).toString();
            // txtLector.setText(nombreLector); // Descomenta si quieres que se auto-llene el filtro también
            
            txtMulta.requestFocus(); 
        }
    }//GEN-LAST:event_tblDetalleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPrestamo1;
    private javax.swing.JButton btnGrabarDevolucion;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDetalle;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtLector;
    private javax.swing.JTextField txtMulta;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
