/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewsBibliotecario;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author VALENTINO
 */
public class jdDevoluciones extends javax.swing.JDialog {
Connection cn; 
DefaultTableModel modelo;
double multaCalculada = 0.0;
int diasRetraso = 0;
    /**
     * Creates new form jdDevoluciones
     */
    public jdDevoluciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configurarTabla();
    }
 private void configurarTabla() {
        modelo = new DefaultTableModel();
        // Agregamos ID Prestamo y Lector para diferenciar porque buscamos por fecha
        modelo.addColumn("ID Prestamo"); 
        modelo.addColumn("Lector");
        modelo.addColumn("ID Ejemplar");
        modelo.addColumn("Título Libro");
        modelo.addColumn("Vence");
        modelo.addColumn("Días Retraso");
        modelo.addColumn("Estado"); // Bueno/Dañado
        tblDetalle.setModel(modelo);
    }
 // Método auxiliar para evitar duplicar cabeceras en el bucle
    private int obtenerIdDevolucionExistente(int idPrestamo) throws SQLException {
        // Busca si ya insertamos una devolución para este préstamo HOY en la BD
        String sql = "SELECT iddevolucion FROM DEVOLUCION WHERE idprestamo = ?";
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setInt(1, idPrestamo);
        ResultSet rs = pst.executeQuery();
        if(rs.next()) return rs.getInt(1);
        return -1;
    }
    // Método auxiliar para Multas (reutilizado de chats anteriores)
    private void generarMultaYBloquear(int idPrestamo, double monto) throws SQLException {
        // 1. Insertar en MULTA
        int idMulta = generarNuevoId("MULTA", "idmulta");
        // Ojo: necesitamos idusuario, lo sacamos con subconsulta rapida
        String sql = "INSERT INTO MULTA (idmulta, idusuario, idprestamo, monto, pagado, fechagenerada) " +
                     "SELECT ?, idusuariolector, ?, ?, FALSE, ? FROM PRESTAMO WHERE idprestamo = ?";
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setInt(1, idMulta);
        pst.setInt(2, idPrestamo);
        pst.setDouble(3, monto);
        pst.setDate(4, java.sql.Date.valueOf(LocalDate.now()));
        pst.setInt(5, idPrestamo);
        pst.executeUpdate();
        
        // 2. Bloquear Usuario
        String sqlBloq = "UPDATE USUARIO SET estado = FALSE WHERE idusuario = (SELECT idusuariolector FROM PRESTAMO WHERE idprestamo = ?)";
        PreparedStatement pstBloq = cn.prepareStatement(sqlBloq);
        pstBloq.setInt(1, idPrestamo);
        pstBloq.executeUpdate();
    }
    
    // Método para generar IDs (secuencial simple)
    private int generarNuevoId(String tabla, String campo) throws SQLException {
        ResultSet rs = cn.createStatement().executeQuery("SELECT MAX(" + campo + ") FROM " + tabla);
        if(rs.next()) return rs.getInt(1) + 1;
        return 1;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFechaPrestamo = new javax.swing.JTextField();
        btnGrabarDevolucion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtLector = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtMulta = new javax.swing.JTextField();
        btnBuscarPrestamo1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Fecha del préstamo:");

        btnGrabarDevolucion.setBackground(new java.awt.Color(24, 118, 210));
        btnGrabarDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGrabarDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnGrabarDevolucion.setText("Registrar Devolución");
        btnGrabarDevolucion.setBorder(null);
        btnGrabarDevolucion.setBorderPainted(false);
        btnGrabarDevolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGrabarDevolucionMouseClicked(evt);
            }
        });
        btnGrabarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarDevolucionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Lector:");

        txtLector.setEditable(false);

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalle);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Multa:");

        txtMulta.setEditable(false);

        btnBuscarPrestamo1.setBackground(new java.awt.Color(24, 118, 210));
        btnBuscarPrestamo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarPrestamo1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPrestamo1.setText("Búscar préstamo");
        btnBuscarPrestamo1.setBorder(null);
        btnBuscarPrestamo1.setBorderPainted(false);
        btnBuscarPrestamo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPrestamo1MouseClicked(evt);
            }
        });
        btnBuscarPrestamo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestamo1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("DEVOLUCIONES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLector, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btnGrabarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(btnBuscarPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrabarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarDevolucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrabarDevolucionMouseClicked

    }//GEN-LAST:event_btnGrabarDevolucionMouseClicked

    private void btnGrabarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarDevolucionActionPerformed
        if (modelo.getRowCount() == 0) return;

        try {
            cn.setAutoCommit(false); // Transacción

            // Recorremos la tabla fila por fila
            for (int i = 0; i < modelo.getRowCount(); i++) {
                
                int idPrestamo = Integer.parseInt(modelo.getValueAt(i, 0).toString());
                int idEjemplar = Integer.parseInt(modelo.getValueAt(i, 2).toString());
                long diasRetraso = Long.parseLong(modelo.getValueAt(i, 5).toString());
                String estadoLibro = modelo.getValueAt(i, 6).toString();
                boolean esBueno = estadoLibro.equalsIgnoreCase("Bueno");
                
                // 1. Verificar si ya existe cabecera de Devolución para este préstamo EN ESTA TRANSACCIÓN
                // (Para no crear 3 devoluciones si Juan devuelve 3 libros del mismo préstamo)
                int idDevolucion = obtenerIdDevolucionExistente(idPrestamo);
                
                if (idDevolucion == -1) {
                    // No existe devolución hoy para este préstamo, la creamos
                    idDevolucion = generarNuevoId("DEVOLUCION", "iddevolucion");
                    double multaTotal = diasRetraso * 5.00; // Logica simple de multa
                    
                    String sqlDev = "INSERT INTO DEVOLUCION (iddevolucion, idprestamo, fechadevolucionreal, multatotal, observaciones) VALUES (?, ?, ?, ?, ?)";
                    PreparedStatement pstDev = cn.prepareStatement(sqlDev);
                    pstDev.setInt(1, idDevolucion);
                    pstDev.setInt(2, idPrestamo);
                    pstDev.setDate(3, java.sql.Date.valueOf(LocalDate.now()));
                    pstDev.setDouble(4, multaTotal);
                    pstDev.setString(5, diasRetraso > 0 ? "Retraso" : "A tiempo");
                    pstDev.executeUpdate();
                    
                    // Si hubo multa, crear registro en tabla MULTA y bloquear usuario
                    if(multaTotal > 0) {
                         generarMultaYBloquear(idPrestamo, multaTotal);
                    }
                }

                // 2. Insertar Detalle Devolución
                int idDetalle = generarNuevoId("DETALLE_DEVOLUCION", "iddetalledev");
                String sqlDet = "INSERT INTO DETALLE_DEVOLUCION (iddetalledev, iddevolucion, idejemplar, estadoejemplar, multa) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement pstDet = cn.prepareStatement(sqlDet);
                pstDet.setInt(1, idDetalle);
                pstDet.setInt(2, idDevolucion);
                pstDet.setInt(3, idEjemplar);
                pstDet.setBoolean(4, esBueno);
                pstDet.setDouble(5, esBueno ? 0.0 : 20.0); // 20 soles si está dañado (ejemplo)
                pstDet.executeUpdate();

                // 3. Liberar Ejemplar
                String sqlLib = "UPDATE EJEMPLAR SET disponible = TRUE WHERE idejemplar = ?";
                PreparedStatement pstLib = cn.prepareStatement(sqlLib);
                pstLib.setInt(1, idEjemplar);
                pstLib.executeUpdate();
                
                // 4. Cerrar Préstamo
                String sqlClose = "UPDATE PRESTAMO SET estado = FALSE WHERE idprestamo = ?";
                PreparedStatement pstClose = cn.prepareStatement(sqlClose);
                pstClose.setInt(1, idPrestamo);
                pstClose.executeUpdate();
            }

            cn.commit();
            JOptionPane.showMessageDialog(this, "Devoluciones procesadas con éxito.");
            modelo.setRowCount(0);
            txtFechaPrestamo.setText("");

        } catch (Exception e) {
            try { cn.rollback(); } catch (SQLException ex) {}
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        } finally {
            try { cn.setAutoCommit(true); } catch (SQLException ex) {}
        }
    }//GEN-LAST:event_btnGrabarDevolucionActionPerformed

    private void btnBuscarPrestamo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPrestamo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPrestamo1MouseClicked

    private void btnBuscarPrestamo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamo1ActionPerformed
       String fecha = txtFechaPrestamo.getText(); // Formato YYYY-MM-DD
        
        // Validar formato básico
        if(!fecha.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Use formato: YYYY-MM-DD (Ej: 2025-05-01)");
            return;
        }

        // QUERY ACTUALIZADA: Busca por fecha y trae datos del lector
        String sql = "SELECT p.idprestamo, u.nombre || ' ' || u.ap_paterno AS lector, " +
                     "p.fechadevolucionestimada, dp.idejemplar, l.titulo " +
                     "FROM PRESTAMO p " +
                     "INNER JOIN USUARIO u ON p.idusuariolector = u.idusuario " +
                     "INNER JOIN DETALLE_PRESTAMO dp ON p.idprestamo = dp.idprestamo " +
                     "INNER JOIN EJEMPLAR e ON dp.idejemplar = e.idejemplar " +
                     "INNER JOIN LIBROS l ON e.idlibro = l.idlibro " +
                     "WHERE p.fechaprestamo = ? AND p.estado = TRUE"; // Solo activos

        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setDate(1, java.sql.Date.valueOf(fecha)); // Convertir String a Date SQL
            ResultSet rs = pst.executeQuery();

            modelo.setRowCount(0);
            LocalDate hoy = LocalDate.now();
            boolean encontrado = false;

            while (rs.next()) {
                encontrado = true;
                
                // Calculamos retraso
                Date sqlFechaLimite = rs.getDate("fechadevolucionestimada");
                long dias = java.time.temporal.ChronoUnit.DAYS.between(sqlFechaLimite.toLocalDate(), hoy);
                if (dias < 0) dias = 0;

                modelo.addRow(new Object[]{
                    rs.getInt("idprestamo"),  // Columna 0: Vital para saber qué cerrar
                    rs.getString("lector"),   // Columna 1: Para ver de quién es
                    rs.getInt("idejemplar"),  // Columna 2
                    rs.getString("titulo"),
                    sqlFechaLimite.toString(),
                    dias,
                    "Bueno" // Estado por defecto
                });
            }

            if (!encontrado) {
                JOptionPane.showMessageDialog(this, "No se encontraron préstamos activos en esa fecha.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarPrestamo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdDevoluciones dialog = new jdDevoluciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPrestamo1;
    private javax.swing.JButton btnGrabarDevolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtFechaPrestamo;
    private javax.swing.JTextField txtLector;
    private javax.swing.JTextField txtMulta;
    // End of variables declaration//GEN-END:variables
}
