/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;

import capaLogica.Ejemplar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author LENOVO
 */
public class ManEjemplar extends javax.swing.JPanel {

    Ejemplar ejem = new Ejemplar();
    private boolean cargandoDesdTabla = false; // <-- AGREGAR ESTA LÍNEA

    DefaultTableModel tabla = new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID Ejemplar", "Nro Ejemplar", "Estado", "Disponibilidad", "Libro"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // NO editable desde la tabla
        }
    };

    public ManEjemplar() {
        initComponents();
        tblEjemplar.setModel(tabla);
        cargarLibros();
        cargarEjemplares();
        // Configuración inicial de botones
        btnInsertar.setText("NUEVO");
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnDarBaja.setEnabled(false);

        txtCodigo.setEnabled(false);
        txtNroEjemplar.setEnabled(false);
    }

    private void cargarEjemplares() {
        try {
            tabla.setRowCount(0);   // limpiar tabla
            ResultSet rs = ejem.listarEjemplares();

            while (rs.next()) {
                tabla.addRow(new Object[]{
                    rs.getInt("idejemplar"),
                    rs.getString("nroejemplar"),
                    rs.getBoolean("estado") ? "Vigente" : "No Vigente", // Ciclo de vida
                    rs.getBoolean("estado_devolucion") ? "Disponible" : "Prestado", // Disponibilidad
                    rs.getString("titulo")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar ejemplares: " + e.getMessage());
        }
    }

    // Cargar títulos en el combo (solo títulos)
    // Cargar títulos en el combo
    private void cargarLibros() {
        try {
            cboLibros.removeAllItems();
            ResultSet rs = ejem.listarTitulosLibros();
            while (rs.next()) {
                String titulo = rs.getString("titulo");
                cboLibros.addItem(titulo);
            }
            cboLibros.setSelectedIndex(-1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar libros: " + e.getMessage());
        }
    }

    private void LimpiarCampos() {
        cargandoDesdTabla = true; // Activar bandera al limpiar

        txtCodigo.setText("");
        txtNroEjemplar.setText("");
        cboLibros.setSelectedIndex(-1);
        checkVigencia.setSelected(false);

        // Configurar botones
        btnInsertar.setText("NUEVO");
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnDarBaja.setEnabled(false);

        // Habilitar campos
        txtNroEjemplar.setEnabled(true);
        cboLibros.setEnabled(true);
        checkVigencia.setEnabled(true);

        cargandoDesdTabla = false; // Desactivar bandera
    }

    // Agregar listener al combo de libros para regenerar código
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboLibros = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtNroEjemplar = new javax.swing.JTextField();
        checkVigencia = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEjemplar = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnDarBaja = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Número Ejemplar");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Estado");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Libro");

        cboLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLibrosActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(24, 118, 210));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar2.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        checkVigencia.setText("Vigente");

        tblEjemplar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEjemplar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEjemplarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEjemplar);

        btnInsertar.setBackground(new java.awt.Color(24, 118, 210));
        btnInsertar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/registrarMarca.png"))); // NOI18N
        btnInsertar.setText("NUEVO");
        btnInsertar.setBorder(null);
        btnInsertar.setBorderPainted(false);
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(24, 118, 210));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/eliminarMarca.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnDarBaja.setBackground(new java.awt.Color(24, 118, 210));
        btnDarBaja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDarBaja.setForeground(new java.awt.Color(255, 255, 255));
        btnDarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/darBajaMarca.png"))); // NOI18N
        btnDarBaja.setText("DAR DE BAJA");
        btnDarBaja.setBorder(null);
        btnDarBaja.setBorderPainted(false);
        btnDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBajaActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(24, 118, 210));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/modificarMarca.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorder(null);
        btnModificar.setBorderPainted(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(24, 118, 210));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/limpiarMarca.png"))); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(null);
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNroEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(cboLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(checkVigencia))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkVigencia))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(cboLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNroEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDarBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        LimpiarCampos();
        cargarEjemplares();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            // Obtener el título seleccionado del combo
            if (cboLibros.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this,
                        "Debe seleccionar un libro del combo para buscar sus ejemplares.",
                        "Libro no seleccionado",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            String tituloLibro = cboLibros.getSelectedItem().toString();

            // Limpiar la tabla
            tabla.setRowCount(0);

            // Buscar ejemplares por título
            ResultSet rs = ejem.buscarEjemplaresPorTitulo(tituloLibro);

            boolean encontrado = false;
            while (rs.next()) {
                encontrado = true;
                tabla.addRow(new Object[]{
                    rs.getInt("idejemplar"),
                    rs.getString("nroejemplar"),
                    rs.getBoolean("estado") ? "Vigente" : "No Vigente",
                    rs.getBoolean("estado_devolucion") ? "Disponible" : "Prestado",
                    rs.getString("titulo")
                });
            }

            if (!encontrado) {
                JOptionPane.showMessageDialog(this,
                        "No se encontraron ejemplares para el libro: " + tituloLibro,
                        "Sin resultados",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al buscar ejemplares: " + e.getMessage(),
                    "Error de búsqueda",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            String idText = txtCodigo.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Seleccione un ejemplar de la tabla para eliminar.");
                return;
            }

            int id = Integer.parseInt(idText);

            // Verificar disponibilidad antes de mostrar confirmación
            if (!ejem.ejemplarEstaDisponible(id)) {
                JOptionPane.showMessageDialog(this,
                        "No se puede eliminar. El ejemplar está actualmente prestado.\n"
                        + "Debe estar disponible para poder eliminarlo.",
                        "Ejemplar no disponible",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Verificar si tiene historial
            boolean tieneHistorialPrestamos = ejem.ejemplarTieneDetallesPrestamo(id);
            boolean tieneHistorialDevoluciones = ejem.ejemplarTieneDetallesDevolucion(id);
            boolean tieneHistorial = tieneHistorialPrestamos || tieneHistorialDevoluciones;

            // Construir mensaje según el historial
            StringBuilder mensaje = new StringBuilder();
            mensaje.append("¿Está seguro de eliminar este ejemplar?\n\n");

            if (tieneHistorial) {
                mensaje.append("⚠️ ADVERTENCIA: Este ejemplar tiene historial registrado:\n");
                if (tieneHistorialPrestamos) {
                    mensaje.append("  • Historial de préstamos\n");
                }
                if (tieneHistorialDevoluciones) {
                    mensaje.append("  • Historial de devoluciones\n");
                }
                mensaje.append("\nSe eliminará el ejemplar y TODO su historial.\n");
            }

            mensaje.append("\n⚠️ Esta acción NO se puede deshacer.");

            int confirmacion = JOptionPane.showConfirmDialog(this,
                    mensaje.toString(),
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                ejem.eliminarEjemplar(id);

                String mensajeExito = "Ejemplar eliminado correctamente";
                if (tieneHistorial) {
                    mensajeExito += "\n(Se eliminó también todo el historial asociado)";
                }

                JOptionPane.showMessageDialog(this, mensajeExito);
                LimpiarCampos();
                cargarEjemplares();
            }

        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "ID inválido");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(),
                    "Error al eliminar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            // Si el botón dice "NUEVO", generar IDs
            if (btnInsertar.getText().equals("NUEVO")) {
                // Validar que haya un libro seleccionado
                if (cboLibros.getSelectedItem() == null) {
                    JOptionPane.showMessageDialog(this, "Seleccione un libro primero.");
                    return;
                }

                // Generar ID
                int nuevoId = ejem.generarIdEjemplar();
                txtCodigo.setText(String.valueOf(nuevoId));

                // Generar código de ejemplar basado en el título del libro
                String titulo = cboLibros.getSelectedItem().toString();
                String nroGenerado = ejem.generarCodigoEjemplar(titulo);
                txtNroEjemplar.setText(nroGenerado);

                txtCodigo.setEnabled(false);
                txtNroEjemplar.setEnabled(false);

                // Marcar como vigente por defecto
                checkVigencia.setSelected(true);

                // Cambiar el texto del botón
                btnInsertar.setText("INSERTAR");

                JOptionPane.showMessageDialog(this,
                        "ID y Número de Ejemplar generados.\n"
                        + "El ejemplar se creará como DISPONIBLE.\n"
                        + "Presione INSERTAR para guardar.");

            } else { // Si el botón dice "INSERTAR", realizar la inserción
                if (cboLibros.getSelectedItem() == null) {
                    JOptionPane.showMessageDialog(this, "Seleccione un libro.");
                    return;
                }

                String titulo = cboLibros.getSelectedItem().toString();
                int idLibro = ejem.buscarIdLibroPorTitulo(titulo);

                if (idLibro == -1) {
                    JOptionPane.showMessageDialog(this, "No se encontró el libro seleccionado.");
                    return;
                }

                String nro = txtNroEjemplar.getText().trim();
                boolean estado = checkVigencia.isSelected();

                if (nro.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "El número de ejemplar no puede estar vacío.");
                    return;
                }

                ejem.insertarEjemplar(idLibro, nro, estado);

                JOptionPane.showMessageDialog(this, "Ejemplar insertado correctamente\n(Estado: Disponible)");
                LimpiarCampos();
                cargarEjemplares();
                txtCodigo.setEnabled(false);
                txtNroEjemplar.setEnabled(false);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaActionPerformed
        try {
            String idText = txtCodigo.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Seleccione un ejemplar de la tabla para dar de baja.");
                return;
            }

            int id = Integer.parseInt(idText);

            // Verificar que el ejemplar ESTÉ DISPONIBLE (no prestado)
            if (!ejem.ejemplarEstaDisponible(id)) {
                JOptionPane.showMessageDialog(this,
                        "No se puede dar de baja. El ejemplar está PRESTADO actualmente.\n"
                        + "Debe estar DISPONIBLE para poder darlo de baja.\n\n"
                        + "Espere a que el ejemplar sea devuelto antes de darlo de baja.",
                        "Ejemplar no disponible",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de dar de baja este ejemplar?\n"
                    + "El ejemplar se marcará como NO VIGENTE.\n"
                    + "Una vez dado de baja, NO podrá ser prestado nuevamente.",
                    "Confirmar baja",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                ejem.darBajaEjemplar(id);

                JOptionPane.showMessageDialog(this,
                        "Ejemplar dado de baja correctamente.\n"
                        + "El ejemplar ya NO podrá ser prestado.");
                LimpiarCampos();
                cargarEjemplares();
            }

        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "ID inválido");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(),
                    "Error al dar de baja", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDarBajaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            String idText = txtCodigo.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Seleccione un ejemplar para modificar.");
                return;
            }

            int id = Integer.parseInt(idText);

            // Verificar que el ejemplar esté disponible antes de modificar
            if (!ejem.ejemplarEstaDisponible(id)) {
                JOptionPane.showMessageDialog(this,
                        "No se puede modificar. El ejemplar está actualmente prestado.\n"
                        + "Debe estar disponible para poder modificarlo.",
                        "Ejemplar no disponible",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (cboLibros.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Seleccione un libro.");
                return;
            }

            String titulo = cboLibros.getSelectedItem().toString();
            int idLibro = ejem.buscarIdLibroPorTitulo(titulo);

            if (idLibro == -1) {
                JOptionPane.showMessageDialog(this, "No se encontró el libro seleccionado.");
                return;
            }

            String nro = txtNroEjemplar.getText().trim();
            boolean estado = checkVigencia.isSelected();

            if (nro.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El número de ejemplar no puede estar vacío.");
                return;
            }

            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de modificar este ejemplar?",
                    "Confirmar modificación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                ejem.modificarEjemplar(id, idLibro, nro, estado);

                JOptionPane.showMessageDialog(this, "Ejemplar modificado correctamente");
                LimpiarCampos();
                cargarEjemplares();
            }

        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "ID inválido");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(),
                    "Error al modificar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblEjemplarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEjemplarMouseClicked
        try {
            int fila = tblEjemplar.getSelectedRow();

            if (fila >= 0) {
                // ACTIVAR bandera para evitar regeneración
                cargandoDesdTabla = true;

                // Obtener datos de la fila seleccionada
                int id = Integer.parseInt(tblEjemplar.getValueAt(fila, 0).toString());
                String nroEjemplar = tblEjemplar.getValueAt(fila, 1).toString();
                String estadoStr = tblEjemplar.getValueAt(fila, 2).toString();
                String disponibilidadStr = tblEjemplar.getValueAt(fila, 3).toString();
                String tituloLibro = tblEjemplar.getValueAt(fila, 4).toString();

                // Llenar los campos
                txtCodigo.setText(String.valueOf(id));
                txtNroEjemplar.setText(nroEjemplar);
                checkVigencia.setSelected(estadoStr.equals("Vigente"));

                // Seleccionar el libro en el combo (esto NO disparará regeneración por la bandera)
                for (int i = 0; i < cboLibros.getItemCount(); i++) {
                    if (cboLibros.getItemAt(i).equals(tituloLibro)) {
                        cboLibros.setSelectedIndex(i);
                        break;
                    }
                }

                // DESACTIVAR bandera después de cargar todo
                cargandoDesdTabla = false;

                // Configurar botones para modo edición
                btnInsertar.setText("NUEVO");

                // Habilitar/deshabilitar botones según disponibilidad
                boolean estaDisponible = disponibilidadStr.equals("Disponible");
                boolean estaVigente = estadoStr.equals("Vigente");

                // MODIFICAR, ELIMINAR y DAR DE BAJA: solo si está disponible (no prestado)
                btnModificar.setEnabled(estaDisponible);
                btnEliminar.setEnabled(estaDisponible);
                btnDarBaja.setEnabled(estaDisponible && estaVigente);

                // Mostrar info según el estado
                if (!estaDisponible) {
                    JOptionPane.showMessageDialog(this,
                            "Este ejemplar está PRESTADO actualmente.\n\n"
                            + "• No se puede MODIFICAR, ELIMINAR ni DAR DE BAJA mientras esté prestado.\n"
                            + "• Espere a que sea devuelto para realizar estas acciones.",
                            "Información del ejemplar",
                            JOptionPane.INFORMATION_MESSAGE);
                } else if (!estaVigente) {
                    JOptionPane.showMessageDialog(this,
                            "Este ejemplar está dado de BAJA (No Vigente).\n\n"
                            + "• Ya no puede ser prestado.\n"
                            + "• Puede MODIFICARLO o ELIMINARLO si es necesario.",
                            "Información del ejemplar",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar datos: " + e.getMessage());
        } finally {
            // Asegurar que la bandera se desactive incluso si hay error
            cargandoDesdTabla = false;
        }
    }//GEN-LAST:event_tblEjemplarMouseClicked

    private void cboLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLibrosActionPerformed
        try {
            // NO regenerar si estamos cargando datos desde la tabla
            if (cargandoDesdTabla) {
                return;
            }

            // Regenerar código en modo INSERCIÓN o MODIFICACIÓN
            boolean modoInsercion = btnInsertar.getText().equals("INSERTAR");
            boolean modoModificacion = !txtCodigo.getText().trim().isEmpty() && btnModificar.isEnabled();

            if ((modoInsercion || modoModificacion) && cboLibros.getSelectedItem() != null) {
                String titulo = cboLibros.getSelectedItem().toString();
                String nroGenerado = ejem.generarCodigoEjemplar(titulo);
                txtNroEjemplar.setText(nroGenerado);
            }
        } catch (Exception e) {
            // No mostrar error aquí para no molestar al usuario
        }
    }//GEN-LAST:event_cboLibrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDarBaja;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboLibros;
    private javax.swing.JCheckBox checkVigencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEjemplar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNroEjemplar;
    // End of variables declaration//GEN-END:variables
}
