/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;

import capaLogica.Ejemplar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author LENOVO
 */
public class ManEjemplar extends javax.swing.JPanel {

    Ejemplar ejem = new Ejemplar();
    DefaultTableModel tabla = new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID Ejemplar", "Nro Ejemplar", "Estado", "Libro"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // NO editable desde la tabla
        }
    };

    public ManEjemplar() {
        initComponents();
        tblEjemplar.setModel(tabla);
        cargarLibros();
        cargarEjemplares();
        // Configuración inicial de botones
        btnInsertar.setText("NUEVO");
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnDarBaja.setEnabled(false);
    }

    private void cargarEjemplares() {
        try {
            tabla.setRowCount(0);   // limpiar tabla
            ResultSet rs = ejem.listarEjemplares();

            while (rs.next()) {
                tabla.addRow(new Object[]{
                    rs.getInt("idejemplar"),
                    rs.getString("nroejemplar"),
                    rs.getBoolean("estado") ? "Vigente" : "No Vigente",
                    rs.getString("titulo")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar ejemplares: " + e.getMessage());
        }
    }

    // Cargar títulos en el combo (solo títulos)
    // Cargar títulos en el combo
    private void cargarLibros() {
        try {
            cboLibros.removeAllItems();
            ResultSet rs = ejem.listarTitulosLibros();
            while (rs.next()) {
                String titulo = rs.getString("titulo");
                cboLibros.addItem(titulo);
            }
            cboLibros.setSelectedIndex(-1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar libros: " + e.getMessage());
        }
    }

    private void LimpiarCampos() {
        txtCodigo.setText("");
        txtNroEjemplar.setText("");
        cboLibros.setSelectedIndex(-1);
        checkVigencia.setSelected(false);

        // Configurar botones
        btnInsertar.setText("NUEVO");
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnDarBaja.setEnabled(false);

        // Habilitar campos
        txtNroEjemplar.setEnabled(true);
        cboLibros.setEnabled(true);
        checkVigencia.setEnabled(true);
    }

    // Agregar listener al combo de libros para regenerar código
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboLibros = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtNroEjemplar = new javax.swing.JTextField();
        checkVigencia = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEjemplar = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnDarBaja = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 430));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Número Ejemplar");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Estado");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Libro");

        cboLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLibrosActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        checkVigencia.setText("Vigente");

        tblEjemplar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEjemplar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEjemplarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEjemplar);

        btnInsertar.setText("NUEVO");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnDarBaja.setText("DAR DE BAJA");
        btnDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBajaActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNroEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkVigencia)
                            .addComponent(cboLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkVigencia))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(cboLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNroEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDarBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        LimpiarCampos();
        cargarEjemplares();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            String filtro = txtNroEjemplar.getText().trim();

            if (filtro.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un número de ejemplar para buscar");
                return;
            }

            ResultSet rs = ejem.buscarEjemplarNroEjemplar(filtro);
            tabla.setRowCount(0);

            boolean encontrado = false;
            while (rs.next()) {
                encontrado = true;
                tabla.addRow(new Object[]{
                    rs.getInt("idejemplar"),
                    rs.getString("nroejemplar"),
                    rs.getBoolean("estado") ? "Activo" : "Inactivo",
                    rs.getString("titulo")
                });
            }

            if (!encontrado) {
                JOptionPane.showMessageDialog(this, "No se encontraron ejemplares con ese número");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al buscar ejemplar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            String idText = txtCodigo.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Seleccione un ejemplar de la tabla para eliminar.");
                return;
            }

            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de eliminar este ejemplar? Esta acción no se puede deshacer.",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                int id = Integer.parseInt(idText);
                ejem.eliminarEjemplar(id);

                JOptionPane.showMessageDialog(this, "Ejemplar eliminado correctamente");
                LimpiarCampos();
                cargarEjemplares();
            }

        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "ID inválido");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(),
                    "Error al eliminar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            // Si el botón dice "NUEVO", generar IDs
            if (btnInsertar.getText().equals("NUEVO")) {
                // Validar que haya un libro seleccionado
                if (cboLibros.getSelectedItem() == null) {
                    JOptionPane.showMessageDialog(this, "Seleccione un libro primero.");
                    return;
                }

                // Generar ID
                int nuevoId = ejem.generarIdEjemplar();
                txtCodigo.setText(String.valueOf(nuevoId));

                // Generar código de ejemplar basado en el título del libro
                String titulo = cboLibros.getSelectedItem().toString();
                String nroGenerado = ejem.generarCodigoEjemplar(titulo);
                txtNroEjemplar.setText(nroGenerado);

                txtCodigo.setEnabled(false);
                txtNroEjemplar.setEnabled(false);

                // Marcar como vigente por defecto
                checkVigencia.setSelected(true);

                // Cambiar el texto del botón
                btnInsertar.setText("INSERTAR");

                JOptionPane.showMessageDialog(this,
                        "ID y Número de Ejemplar generados. Presione INSERTAR para guardar.");

            } else { // Si el botón dice "INSERTAR", realizar la inserción
                if (cboLibros.getSelectedItem() == null) {
                    JOptionPane.showMessageDialog(this, "Seleccione un libro.");
                    return;
                }

                String titulo = cboLibros.getSelectedItem().toString();
                int idLibro = ejem.buscarIdLibroPorTitulo(titulo);

                if (idLibro == -1) {
                    JOptionPane.showMessageDialog(this, "No se encontró el libro seleccionado.");
                    return;
                }

                String nro = txtNroEjemplar.getText().trim();
                boolean estado = checkVigencia.isSelected();

                if (nro.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "El número de ejemplar no puede estar vacío.");
                    return;
                }

                ejem.insertarEjemplar(idLibro, nro, estado);

                JOptionPane.showMessageDialog(this, "Ejemplar insertado correctamente");
                LimpiarCampos();
                cargarEjemplares();
                txtCodigo.setEnabled(true);
                txtNroEjemplar.setEnabled(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaActionPerformed
        try {
            String idText = txtCodigo.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Seleccione un ejemplar de la tabla para dar de baja.");
                return;
            }

            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de dar de baja este ejemplar?",
                    "Confirmar baja",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                int id = Integer.parseInt(idText);
                ejem.darBajaEjemplar(id);

                JOptionPane.showMessageDialog(this, "Ejemplar dado de baja correctamente");
                LimpiarCampos();
                cargarEjemplares();
            }

        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "ID inválido");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(),
                    "Error al dar de baja", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDarBajaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            String idText = txtCodigo.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Seleccione un ejemplar para modificar.");
                return;
            }

            int id = Integer.parseInt(idText);

            if (cboLibros.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Seleccione un libro.");
                return;
            }

            String titulo = cboLibros.getSelectedItem().toString();
            int idLibro = ejem.buscarIdLibroPorTitulo(titulo);

            if (idLibro == -1) {
                JOptionPane.showMessageDialog(this, "No se encontró el libro seleccionado.");
                return;
            }

            String nro = txtNroEjemplar.getText().trim();
            boolean estado = checkVigencia.isSelected();

            if (nro.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El número de ejemplar no puede estar vacío.");
                return;
            }

            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de modificar este ejemplar?",
                    "Confirmar modificación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                ejem.modificarEjemplar(id, idLibro, nro, estado);

                JOptionPane.showMessageDialog(this, "Ejemplar modificado correctamente");
                LimpiarCampos();
                cargarEjemplares();
            }

        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "ID inválido");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(),
                    "Error al modificar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblEjemplarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEjemplarMouseClicked
        try {
            int fila = tblEjemplar.getSelectedRow();

            if (fila >= 0) {
                // Obtener datos de la fila seleccionada
                int id = Integer.parseInt(tblEjemplar.getValueAt(fila, 0).toString());
                String nroEjemplar = tblEjemplar.getValueAt(fila, 1).toString();
                String estadoStr = tblEjemplar.getValueAt(fila, 2).toString();
                String tituloLibro = tblEjemplar.getValueAt(fila, 3).toString();

                // Llenar los campos
                txtCodigo.setText(String.valueOf(id));
                txtNroEjemplar.setText(nroEjemplar);
                checkVigencia.setSelected(estadoStr.equals("Vigente"));

                // Seleccionar el libro en el combo
                for (int i = 0; i < cboLibros.getItemCount(); i++) {
                    if (cboLibros.getItemAt(i).equals(tituloLibro)) {
                        cboLibros.setSelectedIndex(i);
                        break;
                    }
                }

                // Configurar botones para modo edición
                btnInsertar.setText("NUEVO");
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
                btnDarBaja.setEnabled(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar datos: " + e.getMessage());
        }
    }//GEN-LAST:event_tblEjemplarMouseClicked

    private void cboLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLibrosActionPerformed
        try {
        // Solo regenerar si hay un código cargado (modo edición/modificación)
        if (!txtCodigo.getText().trim().isEmpty() && cboLibros.getSelectedItem() != null) {
            String titulo = cboLibros.getSelectedItem().toString();
            String nroGenerado = ejem.generarCodigoEjemplar(titulo);
            txtNroEjemplar.setText(nroGenerado);
        }
    } catch (Exception e) {
        // No mostrar error aquí para no molestar al usuario
    }
    }//GEN-LAST:event_cboLibrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDarBaja;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboLibros;
    private javax.swing.JCheckBox checkVigencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEjemplar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNroEjemplar;
    // End of variables declaration//GEN-END:variables
}
