/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;
import capaLogica.Editorial; 
import java.util.List;
import java.sql.ResultSet; 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author laboratorio_computo
 */
public class ManEditorial extends javax.swing.JPanel {

   Editorial objEditorial = new Editorial();
   DefaultTableModel modeloTabla = new DefaultTableModel();

    /**
     * Creates new form ManEditorial
     */
    public ManEditorial() {
    initComponents();
    inicializarTabla();
    cargarTabla();
    }
    

    private void inicializarTabla() {
        String[] titulos = {"Código", "Nombre", "Teléfono", "Correo", "Vigencia"};
        modeloTabla.setColumnIdentifiers(titulos);
        tbllibros.setModel(modeloTabla);
    }
    
    private void cargarTabla() {
    modeloTabla.setRowCount(0); // Limpiar filas anteriores
    ResultSet rs = null;

    try {
        // 1. Obtener el ResultSet
        // Nota: asumo que la clase Editorial tiene un método llamado listarEditorial()
        rs = objEditorial.listarEditorial(); 

        // 2. Iterar sobre el ResultSet
        while (rs.next()) {
            // Leer los datos del ResultSet (usa nombres de columnas de la BD)
            int id = rs.getInt("ideditorial");
            String nombre = rs.getString("nombre");
            String telefono = rs.getString("telefono");
            String correo = rs.getString("correo");
            boolean estado = rs.getBoolean("estado");
            
            String vigencia = estado ? "Vigente" : "No Vigente";

            Object[] fila = {id, nombre, telefono, correo, vigencia};
            modeloTabla.addRow(fila);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.getMessage(), "Error de Sistema", JOptionPane.ERROR_MESSAGE);
    } 
    /* IMPORTANTE: En la estructura de Categoria.java que me pasaste, la conexión 
    se cierra al final del método DAO (listarCategoria). Si tu Editorial.java hace 
    lo mismo, no necesitas un finally aquí, pero es buena práctica si no lo hace.
    */
}
    
    private void limpiarCampos() {
        txtcodigo.setText("");
        txtnombre.setText("");
        txttelefono.setText("");
        txtcorreo.setText("");
        cbxVigencia.setSelected(false);
        txtcodigo.setEnabled(true); 
        btnBuscar.setEnabled(true);
    }
    
    // Obtiene los datos de la interfaz y los asigna al objeto Editorial
   
    private Editorial obtenerEditorialDesdeCampos() {
        Editorial editorial = new Editorial();

        try {
            String codigoStr = txtcodigo.getText().trim();

            // 🚨 CRÍTICO: Si la cadena está vacía, no se intenta nada y se detiene.
            if (codigoStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo Código es obligatorio.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                return null;
            }

            // Asignar el ID solo después de verificar que no está vacío
            int id = Integer.parseInt(codigoStr);
            editorial.setIdeditorial(id);

            // (Validaciones de otros campos... se asume que pasan o están correctamente implementadas)
            if (txtnombre.getText().trim().isEmpty()
                    || txttelefono.getText().trim().isEmpty()
                    || txtcorreo.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this, "Todos los campos de texto son obligatorios.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                return null;
            }

            editorial.setNombre(txtnombre.getText().trim());
            editorial.setTelefono(txttelefono.getText().trim());
            editorial.setCorreo(txtcorreo.getText().trim());
            editorial.setEstado(cbxVigencia.isSelected());

            return editorial;

        } catch (NumberFormatException e) {
            // Captura si el usuario puso letras en el campo de código
            JOptionPane.showMessageDialog(this, "El Código debe ser un número entero válido.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
            return null;
        } catch (Exception e) {
            // Para cualquier otro error durante la captura de datos
            JOptionPane.showMessageDialog(this, "Error al obtener datos de los campos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        btnlimpiar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btndarbaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllibros = new javax.swing.JTable();
        txttelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbxVigencia = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Código:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 40, 53, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Nombre:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(44, 86, 60, 20);
        jPanel1.add(txtnombre);
        txtnombre.setBounds(112, 86, 210, 26);
        jPanel1.add(txtcodigo);
        txtcodigo.setBounds(110, 40, 110, 26);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar2.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar);
        btnBuscar.setBounds(230, 30, 50, 43);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Correo:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 40, 87, 20);
        jPanel1.add(txtcorreo);
        txtcorreo.setBounds(400, 40, 210, 26);

        btnlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/limpiarMarca.png"))); // NOI18N
        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpiar);
        btnlimpiar.setBounds(330, 180, 130, 43);

        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/eliminarMarca.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminar);
        btneliminar.setBounds(180, 180, 130, 43);

        btnnuevo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/registrarMarca.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevo);
        btnnuevo.setBounds(40, 180, 120, 40);

        btnmodificar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/modificarMarca.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnmodificar);
        btnmodificar.setBounds(610, 180, 129, 43);

        btndarbaja.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btndarbaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/darBajaMarca.png"))); // NOI18N
        btndarbaja.setText("Dar baja");
        btndarbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndarbajaActionPerformed(evt);
            }
        });
        jPanel1.add(btndarbaja);
        btndarbaja.setBounds(470, 180, 130, 43);

        tbllibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Telefono", "Correo", "VIgencia"
            }
        ));
        tbllibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbllibrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbllibros);
        if (tbllibros.getColumnModel().getColumnCount() > 0) {
            tbllibros.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 250, 650, 203);
        jPanel1.add(txttelefono);
        txttelefono.setBounds(112, 138, 210, 26);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Telefono:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(44, 138, 80, 20);

        cbxVigencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxVigencia.setText("Vigente");
        cbxVigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVigenciaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxVigencia);
        cbxVigencia.setBounds(410, 100, 86, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Vigencia:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 100, 80, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String codigoStr = txtcodigo.getText().trim();
        if (codigoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un código para buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ResultSet rs = null;

        try {
            int id = Integer.parseInt(codigoStr);
            // Usamos el método que devuelve ResultSet
            rs = objEditorial.buscarPorCodigo(id);

            if (rs.next()) {
                // Rellenar campos usando los datos del ResultSet
                txtnombre.setText(rs.getString("nombre"));
                txttelefono.setText(rs.getString("telefono"));
                txtcorreo.setText(rs.getString("correo"));
                cbxVigencia.setSelected(rs.getBoolean("estado"));

                txtcodigo.setEnabled(false);
                btnBuscar.setEnabled(false);
                JOptionPane.showMessageDialog(this, "Editorial encontrada.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                limpiarCampos();
                txtcodigo.setText(codigoStr); // Mantiene el código ingresado
                JOptionPane.showMessageDialog(this, "Editorial con código " + id + " no encontrada.", "Búsqueda", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El Código debe ser un número entero.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error de búsqueda: " + e.getMessage(), "Error de Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
    
        limpiarCampos();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        String codigoStr = txtcodigo.getText().trim();
        if (codigoStr.isEmpty() || txtnombre.getText().trim().isEmpty() || txtcodigo.isEnabled()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro para eliminar permanentemente.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¡ADVERTENCIA! ¿Desea ELIMINAR PERMANENTEMENTE la Editorial: " + txtnombre.getText() + "?",
                "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(codigoStr);
                objEditorial.eliminar(id);
                JOptionPane.showMessageDialog(this, "Editorial eliminada permanentemente.", "Eliminación Exitosa", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
                cargarTabla();
            } catch (Exception e) {
                // Aquí capturamos errores de FK si hay libros asociados
                JOptionPane.showMessageDialog(this, "Error al eliminar. Verifique que no haya libros asociados: " + e.getMessage(), "Error de BD", JOptionPane.ERROR_MESSAGE);
            }
        }  
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        try {
            // FASE 1: Preparar para la inserción (Botón dice NUEVO)
            if (btnnuevo.getText().equals("NUEVO")) {
                limpiarCampos();
                txtcodigo.setEnabled(true); // Permitir que el usuario ingrese el ID
                btnnuevo.setText("GUARDAR");

                // FASE 2: Insertar la Editorial (Botón dice GUARDAR)
            } else {

                // 🚨 1. VALIDACIÓN CRÍTICA DEL CÓDIGO Y OTROS CAMPOS (Evita Error NULL)
                String codigoStr = txtcodigo.getText().trim();

                if (codigoStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar un Código (ID) para la Editorial antes de guardar.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Validar que sea un número (para evitar NumberFormatException)
                int idEditorial;
                try {
                    idEditorial = Integer.parseInt(codigoStr);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "El Código debe ser un número entero válido.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Validar campos de texto restantes
                if (txtnombre.getText().trim().isEmpty()
                        || txttelefono.getText().trim().isEmpty()
                        || txtcorreo.getText().trim().isEmpty()) {

                    JOptionPane.showMessageDialog(this, "Nombre, Teléfono y Correo son obligatorios.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // 2. Obtener el objeto Editorial (ya validado)
                Editorial nuevaEditorial = obtenerEditorialDesdeCampos();
                if (nuevaEditorial == null) {
                    return;
                }

                // 3. Verificación de existencia (Maneja el error de "Ya existe...")
                // Usamos .next() para ver si el ResultSet tiene datos.
                if (objEditorial.buscarPorCodigo(nuevaEditorial.getIdeditorial()).next()) {
                    JOptionPane.showMessageDialog(this, "Ya existe una Editorial con este Código (" + nuevaEditorial.getIdeditorial() + "). Debe ingresar un ID diferente.", "Error de Registro", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // 4. Insertamos
                objEditorial.registrar(nuevaEditorial);

                JOptionPane.showMessageDialog(this, "Editorial registrada con éxito.", "Registro", JOptionPane.INFORMATION_MESSAGE);

                // 5. Volver a la normalidad
                btnnuevo.setText("NUEVO");
                limpiarCampos();
                cargarTabla();
            }
        } catch (Exception e) {
            // Capturamos cualquier error de BD restante.
            JOptionPane.showMessageDialog(this, "Error al insertar Editorial: " + e.getMessage(), "Error de BD", JOptionPane.ERROR_MESSAGE);

            // Dejar el botón en modo NUEVO después de la falla.
            btnnuevo.setText("NUEVO");
            txtcodigo.setEnabled(true);
        }
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
          Editorial editorialModificada = obtenerEditorialDesdeCampos();
        if (editorialModificada == null) return; 
        
        try {
            objEditorial.modificar(editorialModificada);
            JOptionPane.showMessageDialog(this, "Editorial modificada con éxito.", "Modificación", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            cargarTabla();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage(), "Error de BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btndarbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndarbajaActionPerformed
         String codigoStr = txtcodigo.getText().trim();
        if (codigoStr.isEmpty() || txtnombre.getText().trim().isEmpty() || txtcodigo.isEnabled()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro para dar de baja.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Desea dar de BAJA la Editorial: " + txtnombre.getText() + "? (Estado = No Vigente)", 
                "Confirmar Baja", JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(codigoStr);
                objEditorial.darBaja(id);
                JOptionPane.showMessageDialog(this, "Editorial dada de BAJA con éxito.", "Baja Exitosa", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
                cargarTabla();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al dar de baja: " + e.getMessage(), "Error de BD", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btndarbajaActionPerformed

    private void tbllibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbllibrosMouseClicked
    int fila = tbllibros.getSelectedRow();
        if (fila == -1) return;
        
        // Obtener datos de la fila
        String codigoStr = modeloTabla.getValueAt(fila, 0).toString();
        String nombre = modeloTabla.getValueAt(fila, 1).toString();
        String telefono = modeloTabla.getValueAt(fila, 2).toString();
        String correo = modeloTabla.getValueAt(fila, 3).toString();
        String vigenciaStr = modeloTabla.getValueAt(fila, 4).toString();
        
        // Rellenar campos de texto
        txtcodigo.setText(codigoStr);
        txtnombre.setText(nombre);
        txttelefono.setText(telefono);
        txtcorreo.setText(correo);
        
        // Rellenar CheckBox
        cbxVigencia.setSelected(vigenciaStr.equals("Vigente"));
        
        // Deshabilitar código para Modificar o Dar Baja
        txtcodigo.setEnabled(false);
        btnBuscar.setEnabled(false);
    }//GEN-LAST:event_tbllibrosMouseClicked

    private void cbxVigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVigenciaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxVigenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btndarbaja;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JCheckBox cbxVigencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbllibros;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
