/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;

import capaLogica.Autor;
import capaLogica.Editorial;
import capaLogica.Categoria;
import capaLogica.Libro;
import capaPrincipal.frmPrincipalBibliotecario;
import java.awt.BorderLayout;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JFrame; // Si MiFormularioPrincipal es un JFrame

/**
 *
 * @author Percy Alexander
 */
public class ManLibro extends javax.swing.JPanel {

    private Libro objLibro = new Libro(); // Asegúrate de tener una instancia de la clase Libro
    private DefaultTableModel modelo;

    Libro Libro = new Libro();
    Editorial editorial = new Editorial();
    Categoria categoria = new Categoria();

    private HashMap<String, Integer> mapCategorias = new HashMap<>();
    private HashMap<String, Integer> mapEditoriales = new HashMap<>();

    /**
     * Creates new form ManLibro
     */
    public ManLibro() {
        initComponents();
        listarLibros();
        inicializarComponentesPersonalizados();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttitulo = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtanio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        chkvigente = new javax.swing.JCheckBox();
        btnlimpiar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btndarbaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllibros = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        cmbEditorial = new javax.swing.JComboBox<>();
        cmbCategoria = new javax.swing.JComboBox<>();
        btnEditorial = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Código:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Título:");

        btnBuscar.setBackground(new java.awt.Color(24, 118, 210));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar2.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Categoría:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Año:");

        chkvigente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkvigente.setText("Vigente");

        btnlimpiar.setBackground(new java.awt.Color(24, 118, 210));
        btnlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/limpiarMarca.png"))); // NOI18N
        btnlimpiar.setText("Limpiar");
        btnlimpiar.setBorder(null);
        btnlimpiar.setBorderPainted(false);
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(24, 118, 210));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/eliminarMarca.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setBorder(null);
        btneliminar.setBorderPainted(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnnuevo.setBackground(new java.awt.Color(24, 118, 210));
        btnnuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/registrarMarca.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.setBorder(null);
        btnnuevo.setBorderPainted(false);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnmodificar.setBackground(new java.awt.Color(24, 118, 210));
        btnmodificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(255, 255, 255));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/modificarMarca.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setBorder(null);
        btnmodificar.setBorderPainted(false);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btndarbaja.setBackground(new java.awt.Color(24, 118, 210));
        btndarbaja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndarbaja.setForeground(new java.awt.Color(255, 255, 255));
        btndarbaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/darBajaMarca.png"))); // NOI18N
        btndarbaja.setText("Dar Baja");
        btndarbaja.setBorder(null);
        btndarbaja.setBorderPainted(false);
        btndarbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndarbajaActionPerformed(evt);
            }
        });

        tbllibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Título", "Editorial", "Categoría", "Año", "Vigencia"
            }
        ));
        tbllibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbllibrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbllibros);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Editorial:");

        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });

        btnEditorial.setText("...");
        btnEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorialActionPerformed(evt);
            }
        });

        btnCategoria.setText("...");
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Vigente:");

        jButton1.setBackground(new java.awt.Color(24, 118, 210));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Asignar autor a libro");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(482, 482, 482))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txttitulo)
                            .addComponent(txtcodigo))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(txtanio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(chkvigente, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnnuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndarbaja, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmodificar)
                            .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chkvigente)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cmbEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEditorial))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCategoria))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btndarbaja, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addGap(3, 3, 3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnlimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarComponentesPersonalizados() {
        try {
            // 1. Cargar Editoriales
            ResultSet rsEdit = editorial.listarEditorialesActivas();
            cargarComboBox(rsEdit, cmbEditorial, mapEditoriales, "ideditorial", "nombre", "-- Seleccione Editorial --");

            // 2. Cargar Categorías
            ResultSet rsCat = categoria.listarCategoriasActivas();
            cargarComboBox(rsCat, cmbCategoria, mapCategorias, "idcategoria", "nombrecategoria", "-- Seleccione Categoría --");

            // ❌ ELIMINADO: Lógica de carga de autores.
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar listas de FK: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarComboBox(ResultSet rs, javax.swing.JComboBox<String> cmb, HashMap<String, Integer> map,
            String idCol, String descCol, String defaultItem) throws Exception {
        cmb.removeAllItems();
        map.clear();
        cmb.addItem(defaultItem);

        if (rs != null) {
            while (rs.next()) {
                Integer id = rs.getInt(idCol);
                String descripcion = rs.getString(descCol);
                cmb.addItem(descripcion);
                map.put(descripcion, id); // Mapeamos el nombre (String) al ID (Integer)
            }
            rs.close();
        }
    }


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            if (txtcodigo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar el Código del Libro para buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Integer idLibro = Integer.parseInt(txtcodigo.getText());
            ResultSet rs = Libro.buscarLibro(idLibro);

            if (rs.next()) {
                txtcodigo.setText(rs.getString("idlibro"));
                txttitulo.setText(rs.getString("titulo"));

                // --- Carga de Claves Foráneas (FK) ---
                Integer idEdit = rs.getInt("ideditorial");
                Integer idCat = rs.getInt("idcategoria");

                // Buscar el NOMBRE en el HashMap dado el ID
                String nomEdit = getKeyFromValue(mapEditoriales, idEdit);
                String nomCat = getKeyFromValue(mapCategorias, idCat);

                cmbEditorial.setSelectedItem(nomEdit);
                cmbCategoria.setSelectedItem(nomCat);
                // -------------------------------------

                txtanio.setText(rs.getString("aniopublicacion"));
                chkvigente.setSelected(rs.getBoolean("estado"));

                rs.close();
                btnnuevo.setText("Nuevo");

            } else {
                JOptionPane.showMessageDialog(this, "El Código de Libro " + idLibro + " no existe.", "No Encontrado", JOptionPane.INFORMATION_MESSAGE);
                limpiarControles();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El código debe ser un número entero válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtcodigo.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar el libro: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        limpiarControles();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        try {
            if (txtcodigo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un libro de la tabla para eliminar.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro que desea eliminar el libro con código " + txtcodigo.getText() + "?",
                    "Confirmar Eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                Libro.eliminarLibro(Integer.parseInt(txtcodigo.getText()));
                JOptionPane.showMessageDialog(this, "Libro eliminado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarControles();
                listarLibros();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El código del libro no es un número válido.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            if (e.getMessage().contains("ERROR_FK")) {
                JOptionPane.showMessageDialog(this,
                        "⛔ No se puede eliminar el Libro. Existen ejemplares o autores asociados.",
                        "Eliminación Bloqueada",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                // Para otros errores (conexión, etc.), muestra el mensaje completo.
                JOptionPane.showMessageDialog(this, "Error al eliminar el libro: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        try {
            if (btnnuevo.getText().equals("Nuevo")) {
                btnnuevo.setText("Guardar");
                limpiarControles();
                txtcodigo.setText(Libro.generarCodigoLibro().toString());
                txtcodigo.setEditable(false);

            } else { // Modo GUARDAR

                String nomEdit = (String) cmbEditorial.getSelectedItem();
                String nomCat = (String) cmbCategoria.getSelectedItem();
                Integer idEditorial = mapEditoriales.get(nomEdit);
                Integer idCategoria = mapCategorias.get(nomCat);

                if (txttitulo.getText().isEmpty() || txtanio.getText().isEmpty() || idEditorial == null || idCategoria == null) {
                    JOptionPane.showMessageDialog(this, "Debe llenar Título, Año y seleccionar Editorial/Categoría válidas.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                Libro.registrar(
                        Integer.parseInt(txtcodigo.getText()), // id
                        txttitulo.getText(), // titulo
                        txtanio.getText(), // anioPublicacion
                        chkvigente.isSelected(), // estado (boolean)
                        idEditorial, // idEditorial
                        idCategoria // idCategoria
                );

                JOptionPane.showMessageDialog(this, "Libro registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                btnnuevo.setText("Nuevo");
                txtcodigo.setEditable(true);

                limpiarControles();
                listarLibros(); // Refresca la tabla
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "El campo Código o Año debe ser un número válido.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
            btnnuevo.setText("Guardar");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al procesar Libro: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            btnnuevo.setText("Nuevo"); // Regresar al estado inicial si hay un error grave de BD
            txtcodigo.setEditable(true);
        }
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        try {
            // 1. Obtener IDs usando el HashMap
            String nomEdit = (String) cmbEditorial.getSelectedItem();
            String nomCat = (String) cmbCategoria.getSelectedItem();
            Integer idEditorial = mapEditoriales.get(nomEdit);
            Integer idCategoria = mapCategorias.get(nomCat);

            // 2. Validación
            if (txtcodigo.getText().isEmpty() || txttitulo.getText().isEmpty() || txtanio.getText().isEmpty() || idEditorial == null || idCategoria == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un libro y llenar todos los campos.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Integer idLibro = Integer.parseInt(txtcodigo.getText());

            // MODIFICAR
            Libro.modificar(idLibro, txttitulo.getText(), txtanio.getText(), chkvigente.isSelected(), idEditorial, idCategoria);

            JOptionPane.showMessageDialog(this, "Libro modificado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            limpiarControles();
            listarLibros();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar el libro: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btndarbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndarbajaActionPerformed
        try {
            if (txtcodigo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un libro para cambiar su estado.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Determina el nuevo estado (lo opuesto al actual)
            Boolean nuevoEstado = !chkvigente.isSelected();
            String mensajeEstado = nuevoEstado ? "dar de ALTA" : "dar de BAJA";

            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro que desea " + mensajeEstado + " el libro con código " + txtcodigo.getText() + "?",
                    "Confirmar Cambio de Estado",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                Libro.modificarVigencia(Integer.parseInt(txtcodigo.getText()), nuevoEstado);
                JOptionPane.showMessageDialog(this, "Estado del libro cambiado a " + (nuevoEstado ? "VIGENTE" : "NO VIGENTE") + " exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                if (nuevoEstado) {
                    btndarbaja.setText("Dar Baja"); // Ya está en alta, la próxima es baja
                } else {
                    btndarbaja.setText("Dar Alta"); // Ya está en baja, la próxima es alta
                }

                limpiarControles();
                listarLibros();
            }
        } catch (Exception e) {
            // 🚨 Manejo de ERROR_PRESTAMO_ACTIVO
            if (e.getMessage().contains("ERROR_PRESTAMO_ACTIVO")) {
                JOptionPane.showMessageDialog(this,
                        "⚠️ No se puede dar de BAJA. El libro tiene ejemplares actualmente prestados.",
                        "Imposible Inactivar",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                // Para otros errores (BD, conexión, etc.)
                JOptionPane.showMessageDialog(this, "Error al cambiar el estado del libro: " + e.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btndarbajaActionPerformed

    public <T, E> T getKeyFromValue(HashMap<T, E> map, E value) {
        for (Map.Entry<T, E> entry : map.entrySet()) {
            if (entry.getValue().equals(value)) {
                return entry.getKey();
            }
        }
        return null;
    }

    private void tbllibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbllibrosMouseClicked
        int fila = tbllibros.getSelectedRow();

        if (fila != -1) {
            btnnuevo.setText("Nuevo");
            txtcodigo.setEditable(true);

            try {
                // ... (Lectura de campos) ...
                String codigo = String.valueOf(tbllibros.getValueAt(fila, 0)).trim();
                String titulo = String.valueOf(tbllibros.getValueAt(fila, 1)).trim();
                String editorialNombre = String.valueOf(tbllibros.getValueAt(fila, 2)).trim();
                String categoriaNombre = String.valueOf(tbllibros.getValueAt(fila, 3)).trim();
                String anio = String.valueOf(tbllibros.getValueAt(fila, 4)).trim();
                String estado = String.valueOf(tbllibros.getValueAt(fila, 5)).trim(); // Índice 5: Vigencia

                txtcodigo.setText(codigo);
                txttitulo.setText(titulo);
                txtanio.setText(anio);

                // 2. Asignar a JCheckBox
                chkvigente.setSelected(estado.equalsIgnoreCase("Vigente"));

                // 3. Asignar a JComboBox
                cmbEditorial.setSelectedItem(editorialNombre);
                cmbCategoria.setSelectedItem(categoriaNombre);

                // 🌟 CÓDIGO AÑADIDO: Actualizar el texto del botón 🌟
                // Si el estado actual es VIGENTE, el botón debe decir "Dar Baja".
                // Si el estado actual es NO VIGENTE, el botón debe decir "Dar Alta".
                if (estado.equalsIgnoreCase("Vigente")) {
                    btndarbaja.setText("Dar Baja");
                } else {
                    btndarbaja.setText("Dar Alta");
                }
                // 🌟 FIN DEL CÓDIGO AÑADIDO 🌟

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar datos de la fila: " + e.getMessage(), "Error General", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tbllibrosMouseClicked

    private void btnEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorialActionPerformed
        javax.swing.JFrame frameContenedor = new javax.swing.JFrame("Buscar Editorial");

        // 2. Crear la instancia de BuscarEditorial, usando el constructor
        //    que requiere la referencia del panel principal (this) y el contenedor.
        BuscarEditorial panelEditorial = new BuscarEditorial(this, frameContenedor);

        // 3. Configurar y mostrar el frame
        frameContenedor.setContentPane(panelEditorial);
        frameContenedor.revalidate();
        frameContenedor.pack();
        frameContenedor.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        frameContenedor.setLocationRelativeTo(null);
        frameContenedor.setVisible(true);
    }//GEN-LAST:event_btnEditorialActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        javax.swing.JFrame frameContenedor = new javax.swing.JFrame("Buscar Categoría");

        BuscarCategoria panelCategoria = new BuscarCategoria(this, frameContenedor);

        frameContenedor.setContentPane(panelCategoria);
        frameContenedor.revalidate();
        frameContenedor.pack();
        frameContenedor.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        frameContenedor.setLocationRelativeTo(null);
        frameContenedor.setVisible(true);
    }//GEN-LAST:event_btnCategoriaActionPerformed

    public void setCategoriaSeleccionada(int idCategoria, String nombreCategoria) {
        try {
            // 1. Asegurarse de que el mapa contenga la nueva categoría.
            // Si no está, la añadimos (esto es importante si la categoría
            // fue creada recientemente o si el filtro no la trajo).
            if (!mapCategorias.containsKey(nombreCategoria)) {
                // IMPORTANTE: Asegúrate de que el DefaultComboBoxModel lo permita
                cmbCategoria.addItem(nombreCategoria);
                mapCategorias.put(nombreCategoria, idCategoria);
            }

            // 2. Seleccionar el ítem en el JComboBox
            cmbCategoria.setSelectedItem(nombreCategoria);

            // Opcional: enfocar el siguiente campo
            txtanio.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la categoría seleccionada: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void setEditorialSeleccionada(int idEditorial, String nombreEditorial) {
        try {
            // 1. Asegurarse de que el mapa contenga la nueva editorial.
            if (!mapEditoriales.containsKey(nombreEditorial)) {
                // Agregamos el nuevo item al JComboBox y al HashMap
                cmbEditorial.addItem(nombreEditorial);
                mapEditoriales.put(nombreEditorial, idEditorial);
            }

            // 2. Seleccionar el ítem en el JComboBox
            cmbEditorial.setSelectedItem(nombreEditorial);

            // Opcional: enfocar el siguiente campo (Categoría)
            cmbCategoria.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar la editorial seleccionada: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManAsignarAutorLibro panelAsignar = new ManAsignarAutorLibro();
        javax.swing.JDialog dialogo;

        java.awt.Window owner = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (owner instanceof java.awt.Frame) {
            dialogo = new javax.swing.JDialog((java.awt.Frame) owner, "Asignar Autor a Libro", true);
        } else if (owner instanceof java.awt.Dialog) {
            dialogo = new javax.swing.JDialog((java.awt.Dialog) owner, "Asignar Autor a Libro", true);
        } else {
            dialogo = new javax.swing.JDialog((java.awt.Frame) null, "Asignar Autor a Libro", true);
        }

        dialogo.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);

        dialogo.setContentPane(panelAsignar);
        dialogo.pack();
        dialogo.setLocationRelativeTo(owner);
        dialogo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listarLibros() {
        ResultSet rs = null;
        try {
            rs = objLibro.listarLibros();

            modelo = new DefaultTableModel();

            // 1. Definición con 6 columnas, acorde a tu diseño actual
            String[] columnas = {
                "Código", "Título", "Editorial", "Categoría", "Año", "Vigencia"
            };
            modelo.setColumnIdentifiers(columnas);

            // 2. Llenar el modelo con los 6 datos del ResultSet
            while (rs.next()) {
                String estado = rs.getBoolean("estado") ? "Vigente" : "No Vigente";

                Object[] fila = {
                    rs.getInt("idlibro"), // Índice 0: Código
                    rs.getString("titulo"), // Índice 1: Título
                    rs.getString("nombre_editorial"), // Índice 2: Editorial
                    rs.getString("nombre_categoria"), // Índice 3: Categoría
                    rs.getString("aniopublicacion"), // Índice 4: Año
                    estado // Índice 5: Vigencia
                };
                modelo.addRow(fila);
            }

            tbllibros.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la lista de libros: " + e.getMessage(), "Error de Listado", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                }
            }
        }
    }

    private void limpiarControles() {
        txtcodigo.setText("");
        txtanio.setText("");
        txttitulo.setText("");
        chkvigente.setSelected(false);
        cmbEditorial.setSelectedIndex(0);
        cmbCategoria.setSelectedIndex(0);
        txtcodigo.setEditable(true);
        txttitulo.requestFocus();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnEditorial;
    private javax.swing.JButton btndarbaja;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JCheckBox chkvigente;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbEditorial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbllibros;
    private javax.swing.JTextField txtanio;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
