package viewsBibliotecario;

import capaLogica.Usuarios;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FABIAN VERA
 */
public class ManUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form ManUsuarios
     */
    public ManUsuarios() {
        initComponents();
        listarUsuarios();
        listarTipoUsuarios();
    }

    Usuarios objUsuarios = new Usuarios();
    ResultSet rs = null;

    private void listarUsuarios() {
        ResultSet rsUsuarios = null;
        DefaultTableModel modeloU = new DefaultTableModel();

        // Columnas de la tabla
        modeloU.addColumn("ID");
        modeloU.addColumn("Nombre");
        modeloU.addColumn("Ap_Paterno");
        modeloU.addColumn("Ap_Materno");
        modeloU.addColumn("Fecha_Nacimiento");
        modeloU.addColumn("Usuario");
        modeloU.addColumn("Contraseña");
        modeloU.addColumn("Teléfono");
        modeloU.addColumn("Correo");
        modeloU.addColumn("Dirección");
        modeloU.addColumn("Tipo");
        modeloU.addColumn("Estado");

        tblUsuarios.setModel(modeloU);

        try {
            rsUsuarios = objUsuarios.listarUsuarios();

            while (rsUsuarios.next()) {

                String estado = rsUsuarios.getBoolean("estado") ? "Si" : "No";

                modeloU.addRow(new Object[]{
                    rsUsuarios.getInt("idusuario"),
                    rsUsuarios.getString("nombre"),
                    rsUsuarios.getString("ap_paterno"),
                    rsUsuarios.getString("ap_materno"),
                    rsUsuarios.getDate("f_nacimiento"),
                    rsUsuarios.getString("nomusuario"),
                    rsUsuarios.getString("contrasenia"),
                    rsUsuarios.getString("telefono"),
                    rsUsuarios.getString("correo"),
                    rsUsuarios.getString("direccion"),
                    rsUsuarios.getString("tipousuario"),
                    estado
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al listar usuarios: " + e.getMessage());
        }
    }

    private void limpiarControles() {
        txtId.setEnabled(true);
        chkvigente.setEnabled(true);
        txtContrasena.setEnabled(true);
        txtId.setText("");
        txtNombre.setText("");
        txtApPaterno.setText("");
        txtApMaterno.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtContrasena.setText("");
        txtGmail.setText("");
        txtUsuario.setText("");
        jDateChooser1.setDate(null);
        if (cboTipo.getItemCount() > 0) {
            cboTipo.setSelectedIndex(0);
        }
        chkvigente.setSelected(false);
        tblUsuarios.clearSelection();
    }

    private void limpiarControlesRegistrar() {
        btnNuevo.setText("NUEVO");
        txtId.setEnabled(true);
        chkvigente.setEnabled(true);
        txtContrasena.setEnabled(true);
        txtId.setText("");
        txtNombre.setText("");
        txtApPaterno.setText("");
        txtApMaterno.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtContrasena.setText("");
        txtGmail.setText("");
        txtUsuario.setText("");
        jDateChooser1.setDate(null);
        if (cboTipo.getItemCount() > 0) {
            cboTipo.setSelectedIndex(0);
        }
        chkvigente.setSelected(false);
        tblUsuarios.clearSelection();
    }

    private void listarTipoUsuarios() {
        DefaultComboBoxModel modeloTU = new DefaultComboBoxModel();
        cboTipo.setModel(modeloTU);
        modeloTU.addElement("lector");
        modeloTU.addElement("bibliotecario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtApPaterno = new javax.swing.JTextField();
        txtGmail = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        chkvigente = new javax.swing.JCheckBox();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnDarbaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        cboTipo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtApMaterno = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtContrasena = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Email:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Apellido Paterno:");

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Fecha Nacimiento:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Contraseña:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Usuario:");

        chkvigente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkvigente.setText("Vigente");

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnDarbaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDarbaja.setText("DAR BAJA");
        btnDarbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarbajaActionPerformed(evt);
            }
        });

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Vigente:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Apellido Materno:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Teléfono:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Nombre:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Dirección:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Tipo:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Id:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(chkvigente, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(10, 10, 10)
                                .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDarbaja, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkvigente)
                        .addComponent(jLabel13)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnModificar)
                    .addComponent(btnNuevo)
                    .addComponent(btnDarbaja)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void cargarDatosDesdeTabla() {
        txtId.setEnabled(false);
        txtContrasena.setEnabled(true);

        int fila = tblUsuarios.getSelectedRow();

        if (fila >= 0) {

            txtId.setText(tblUsuarios.getValueAt(fila, 0).toString());
            txtNombre.setText(tblUsuarios.getValueAt(fila, 1).toString());
            txtApPaterno.setText(tblUsuarios.getValueAt(fila, 2).toString());
            txtApMaterno.setText(tblUsuarios.getValueAt(fila, 3).toString());
            java.util.Date fecha = (java.util.Date) tblUsuarios.getValueAt(fila, 4);
            jDateChooser1.setDate(fecha);
            txtUsuario.setText(tblUsuarios.getValueAt(fila, 5).toString());
            txtTelefono.setText(tblUsuarios.getValueAt(fila, 7).toString());
            txtGmail.setText(tblUsuarios.getValueAt(fila, 8).toString());
            txtDireccion.setText(tblUsuarios.getValueAt(fila, 9).toString());
            cboTipo.setSelectedItem(tblUsuarios.getValueAt(fila, 10).toString());

            Object est = tblUsuarios.getValueAt(fila, 11);

            if (est instanceof Boolean) {
                chkvigente.setSelected((Boolean) est);

            } else {
                String valor = est.toString().trim().toLowerCase();

                chkvigente.setSelected(
                        valor.equals("vigente")
                        || valor.equals("true")
                        || valor.equals("t")
                        || valor.equals("1")
                        || valor.equals("si")
                        || valor.equals("activo")
                );
            }
        }

    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        txtId.setEnabled(false);
        txtContrasena.setEnabled(true);

        try {
            String idTexto = txtId.getText().trim();
            String usuarioTexto = txtUsuario.getText().trim();

            if (idTexto.equals("") && usuarioTexto.equals("")) {
                JOptionPane.showMessageDialog(this, "Debe ingresar ID o nombre de usuario para buscar");
                return;
            }

            if (!idTexto.equals("")) {
                rs = objUsuarios.buscarUsuario(Integer.parseInt(idTexto));
            } else {
                rs = objUsuarios.buscarUsuarioPorNombre(usuarioTexto);
            }

            if (rs.next()) {

                txtId.setText(String.valueOf(rs.getInt("idusuario")));
                txtNombre.setText(rs.getString("nombre"));
                txtApPaterno.setText(rs.getString("ap_paterno"));
                txtApMaterno.setText(rs.getString("ap_materno"));
                txtUsuario.setText(rs.getString("nomusuario"));
                txtTelefono.setText(rs.getString("telefono"));
                txtGmail.setText(rs.getString("correo"));
                txtDireccion.setText(rs.getString("direccion"));
                cboTipo.setSelectedItem(rs.getString("tipousuario"));
                chkvigente.setSelected(rs.getBoolean("estado"));
                jDateChooser1.setDate(rs.getDate("f_nacimiento"));
                DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
                modelo.setRowCount(0);
                Object[] fila = new Object[]{
                    rs.getInt("idusuario"),
                    rs.getString("nombre"),
                    rs.getString("ap_paterno"),
                    rs.getString("ap_materno"),
                    rs.getDate("f_nacimiento"),
                    rs.getString("nomusuario"),
                    rs.getString("contrasenia"),
                    rs.getString("telefono"),
                    rs.getString("correo"),
                    rs.getString("direccion"),
                    rs.getString("tipousuario"),
                    rs.getBoolean("estado") ? "Vigente" : "No Vigente"
                };
                modelo.addRow(fila);
                rs.close();
            } else {
                JOptionPane.showMessageDialog(this, "Usuario no existe!");
                limpiarControles();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarControlesRegistrar();
        listarUsuarios();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            if (txtId.getText().trim().equals("")) {

                JOptionPane.showMessageDialog(this,
                        "Debe ingresar un ID de usuario para eliminar");

            } else {

                int op = JOptionPane.showOptionDialog(
                        null,
                        "¿Está seguro que desea eliminar al usuario "
                        + txtNombre.getText() + " "
                        + txtApPaterno.getText() + "?",
                        "Confirmación",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        new Object[]{"Sí", "No"},
                        "Sí"
                );

                if (op == 0) {

                    objUsuarios.eliminarUsuario(
                            Integer.parseInt(txtId.getText())
                    );

                    JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente.");

                    limpiarControles();
                    listarUsuarios();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        try {
            if (btnNuevo.getText().equals("NUEVO")) {
                btnNuevo.setText("GUARDAR");
                limpiarControles();
                chkvigente.setEnabled(false);
                txtId.setEnabled(false);
                chkvigente.setSelected(true);
                jDateChooser1.setCalendar(null);
                txtId.setText(objUsuarios.generarCodigoUsuario().toString());
            } else if (btnNuevo.getText().equals("GUARDAR")) {

                if (txtNombre.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar el nombre");
                    return;
                }

                if (txtApPaterno.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar el apellido paterno");
                    return;
                }

                if (txtApMaterno.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar el apellido materno");
                    return;
                }

                if (jDateChooser1.getDate() == null) {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar la fecha de nacimiento");
                    return;
                }

                Date fechaSeleccionada = jDateChooser1.getDate();
                Date hoy = new Date();

                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                fechaSeleccionada = formato.parse(formato.format(fechaSeleccionada));
                hoy = formato.parse(formato.format(hoy));

                // No puede ser futura
                if (fechaSeleccionada.after(hoy)) {
                    JOptionPane.showMessageDialog(this,
                            "La fecha de nacimiento no puede ser futura.",
                            "Fecha inválida",
                            JOptionPane.WARNING_MESSAGE);
                    jDateChooser1.requestFocus();
                    return;
                }

                // Mínimo 12 años
                long diferenciaMS = hoy.getTime() - fechaSeleccionada.getTime();
                long años = diferenciaMS / (1000L * 60 * 60 * 24 * 365);

                if (años < 12) {
                    JOptionPane.showMessageDialog(this,
                            "El usuario debe tener al menos 12 años.",
                            "Edad mínima",
                            JOptionPane.WARNING_MESSAGE);
                    jDateChooser1.requestFocus();
                    return;
                }

                if (txtUsuario.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar el usuario");
                    return;
                }

                if (txtContrasena.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar la contraseña");
                    return;
                }

                if (txtTelefono.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar el teléfono");
                    return;
                }

                // VALIDACIÓN DE TELÉFONO
                String telefono = txtTelefono.getText().trim();
                if (!telefono.matches("^[0-9]{9}$")) {
                    JOptionPane.showMessageDialog(this,
                            "El teléfono debe contener exactamente 9 dígitos.",
                            "Teléfono inválido",
                            JOptionPane.WARNING_MESSAGE);
                    txtTelefono.requestFocus();
                    return;
                }

                if (txtGmail.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar el correo");
                    return;
                }

                // VALIDACIÓN DE CORREO
                String correo = txtGmail.getText().trim();
                if (!correo.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$")) {
                    JOptionPane.showMessageDialog(this,
                            "Debe ingresar un correo electrónico válido.",
                            "Correo inválido",
                            JOptionPane.WARNING_MESSAGE);
                    txtGmail.requestFocus();
                    return;
                }

                if (txtDireccion.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar la dirección");
                    return;
                }

                if (cboTipo.getSelectedIndex() == -1) {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de usuario");
                    return;
                }

                java.util.Date fechaUtil = jDateChooser1.getDate();
                java.sql.Date fechaNacimiento = new java.sql.Date(fechaUtil.getTime());

                int op = JOptionPane.showOptionDialog(
                        null,
                        "¿Está seguro que desea registrar al usuario "
                        + txtNombre.getText() + " "
                        + txtApPaterno.getText() + "?",
                        "Confirmación de Registro",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        new Object[]{"Sí", "No"},
                        "Sí"
                );

                if (op != JOptionPane.YES_OPTION) {
                    return; // usuario canceló
                }

                objUsuarios.registrar(Integer.valueOf(txtId.getText()),
                        txtNombre.getText(),
                        txtApPaterno.getText(),
                        txtApMaterno.getText(),
                        fechaNacimiento.toString(),
                        txtUsuario.getText(),
                        txtContrasena.getText(),
                        txtTelefono.getText(),
                        txtGmail.getText(),
                        txtDireccion.getText(),
                        cboTipo.getSelectedItem().toString()
                );

                JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente.");

                limpiarControles();
                listarUsuarios();

                btnNuevo.setText("NUEVO");
            } else {
                btnNuevo.setText("NUEVO");
                limpiarControles();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        txtId.setEnabled(false);

        try {

            // VALIDACIONES
            if (txtId.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario.");
                return;
            }

            if (txtNombre.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar el nombre.");
                return;
            }

            if (!txtNombre.getText().matches("^[A-Za-zÁÉÍÓÚáéíóúñÑ ]+$")) {
                JOptionPane.showMessageDialog(this,
                        "El nombre solo debe contener letras.",
                        "Nombre inválido",
                        JOptionPane.WARNING_MESSAGE);
                txtNombre.requestFocus();
                return;
            }

            if (txtApPaterno.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar el apellido paterno.");
                return;
            }

            if (!txtApPaterno.getText().matches("^[A-Za-zÁÉÍÓÚáéíóúñÑ ]+$")) {
                JOptionPane.showMessageDialog(this,
                        "El apellido paterno solo debe contener letras.",
                        "Apellido inválido",
                        JOptionPane.WARNING_MESSAGE);
                txtApPaterno.requestFocus();
                return;
            }

            if (txtApMaterno.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar el apellido materno.");
                return;
            }

            if (!txtApMaterno.getText().matches("^[A-Za-zÁÉÍÓÚáéíóúñÑ ]+$")) {
                JOptionPane.showMessageDialog(this,
                        "El apellido materno solo debe contener letras.",
                        "Apellido inválido",
                        JOptionPane.WARNING_MESSAGE);
                txtApMaterno.requestFocus();
                return;
            }

            if (jDateChooser1.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar la fecha de nacimiento.");
                return;
            }

            if (txtUsuario.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar el usuario.");
                return;
            }

            if (txtContrasena.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar la contraseña.");
                return;
            }

            if (txtTelefono.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar el teléfono.");
                return;
            }

            // VALIDACIÓN DE TELÉFONO
            String telefono = txtTelefono.getText().trim();
            if (!telefono.matches("^[0-9]{9}$")) {
                JOptionPane.showMessageDialog(this,
                        "El teléfono debe contener exactamente 9 dígitos.",
                        "Teléfono inválido",
                        JOptionPane.WARNING_MESSAGE);
                txtTelefono.requestFocus();
                return;
            }

            if (txtGmail.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar el correo.");
                return;
            }

            // VALIDACIÓN DE CORREO
            String correo = txtGmail.getText().trim();
            if (!correo.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$")) {
                JOptionPane.showMessageDialog(this,
                        "Debe ingresar un correo electrónico válido.",
                        "Correo inválido",
                        JOptionPane.WARNING_MESSAGE);
                txtGmail.requestFocus();
                return;
            }

            if (txtDireccion.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar la dirección.");
                return;
            }

            if (cboTipo.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de usuario.");
                return;
            }

            // FECHA
            java.util.Date fechaUtil = jDateChooser1.getDate();
            java.sql.Date fechaNacimiento = new java.sql.Date(fechaUtil.getTime());

            // CONFIRMACIÓN
            int op = JOptionPane.showOptionDialog(
                    null,
                    "¿Está seguro que desea modificar al usuario "
                    + txtNombre.getText() + " "
                    + txtApPaterno.getText() + "?",
                    "Confirmación de Modificación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    new Object[]{"Sí", "No"},
                    "Sí"
            );

            if (op != JOptionPane.YES_OPTION) {
                return;
            }

            objUsuarios.modificar(
                    Integer.parseInt(txtId.getText()),
                    txtNombre.getText(),
                    txtApPaterno.getText(),
                    txtApMaterno.getText(),
                    fechaNacimiento,
                    txtUsuario.getText(),
                    txtContrasena.getText(),
                    txtTelefono.getText(),
                    txtGmail.getText(),
                    txtDireccion.getText(),
                    cboTipo.getSelectedItem().toString(),
                    chkvigente.isSelected()
            );

            JOptionPane.showMessageDialog(this, "Usuario modificado exitosamente.");

            limpiarControles();
            listarUsuarios();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnDarbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarbajaActionPerformed
        try {

            if (txtId.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario para dar de baja.");
                return;
            }

            // Verificar si ya está dado de baja
            boolean vigente = chkvigente.isSelected();

            if (!vigente) {
                JOptionPane.showMessageDialog(this,
                        "El usuario ya está dado de baja.",
                        "Aviso",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Confirmación de baja
            int op = JOptionPane.showOptionDialog(
                    null,
                    "¿Está seguro que desea dar de baja al usuario "
                    + txtNombre.getText() + " "
                    + txtApPaterno.getText() + "?",
                    "Confirmación de Baja",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    new Object[]{"Sí", "No"},
                    "Sí"
            );

            if (op != JOptionPane.YES_OPTION) {
                return;
            }

            objUsuarios.darBajaUsuario(Integer.parseInt(txtId.getText()));

            JOptionPane.showMessageDialog(this, "Usuario dado de baja exitosamente.");

            limpiarControles();
            listarUsuarios();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnDarbajaActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        cargarDatosDesdeTabla();
    }//GEN-LAST:event_tblUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDarbaja;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JCheckBox chkvigente;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
