/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edgar Bernabe
 */
public class Multa extends javax.swing.JPanel {
    capaLogica.Multa objMulta = new capaLogica.Multa();
    DefaultTableModel modelo;
    /**
     * Creates new form Multa
     */
    public Multa() {
        initComponents();
        listarMultas();
    }
    
    private void listarMultas() {
        ResultSet rs = null;
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Lector");
        modelo.addColumn("F. Generada");
        modelo.addColumn("Monto");
        modelo.addColumn("Estado");

        tblMultas.setModel(modelo);
        
        double total = 0.0;

        try {
            // Obtener filtros de los cuadros de texto
            String fecha = txtFechaPrestamo.getText().trim();
            String lector = txtLector.getText().trim();

            rs = objMulta.listarMultas(fecha, lector);

            while (rs.next()) {
                boolean pagado = rs.getBoolean("pagado");
                String estado = pagado ? "Pagado" : "Pendiente";
                double monto = rs.getDouble("monto");

                modelo.addRow(new Object[]{
                    rs.getInt("idmulta"),
                    rs.getString("nombre_completo"),
                    rs.getDate("fechagenerada"),
                    monto,
                    estado
                });
                
                // Sumar al total solo si está pendiente (Opcional: sumar todo si prefieres)
                // En este caso, sumaremos todo lo que se muestra en la tabla
                 total += monto;
            }
            
            lblTotal.setText(String.format("%.2f", total));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al listar multas: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFechaPrestamo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLector = new javax.swing.JTextField();
        btnBuscarPrestamo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMultas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnPagarMulta = new javax.swing.JButton();

        jLabel1.setText("Fecha del Multa:");

        jLabel2.setText("Lector:");

        btnBuscarPrestamo.setText("Buscar Multas");
        btnBuscarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestamoActionPerformed(evt);
            }
        });

        tblMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMultas);

        jLabel3.setText("TOTAL:");

        lblTotal.setText("0.0");

        btnPagarMulta.setText("PAGAR MULTA");
        btnPagarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarMultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtLector, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(btnBuscarPrestamo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(lblTotal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPagarMulta))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarPrestamo)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTotal)
                    .addComponent(btnPagarMulta))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarMultaActionPerformed
        int fila = tblMultas.getSelectedRow();
        
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una multa de la tabla para pagarla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String estadoActual = tblMultas.getValueAt(fila, 4).toString(); // Columna 4 es Estado
        if (estadoActual.equalsIgnoreCase("Pagado")) {
            JOptionPane.showMessageDialog(this, "Esta multa ya está pagada.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int idMulta = Integer.parseInt(tblMultas.getValueAt(fila, 0).toString()); // Columna 0 es ID
        String lector = tblMultas.getValueAt(fila, 1).toString();
        double monto = Double.parseDouble(tblMultas.getValueAt(fila, 3).toString());

        int confirm = JOptionPane.showConfirmDialog(this, 
                "¿Confirmar pago de multa?\nLector: " + lector + "\nMonto: S/ " + monto, 
                "Confirmar Pago", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                objMulta.pagarMulta(idMulta);
                JOptionPane.showMessageDialog(this, "Pago registrado correctamente.");
                listarMultas(); // Actualizar la tabla
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al procesar el pago: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnPagarMultaActionPerformed

    private void btnBuscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamoActionPerformed
        listarMultas();
    }//GEN-LAST:event_btnBuscarPrestamoActionPerformed

    private void tblMultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMultasMouseClicked
        int fila = tblMultas.getSelectedRow();
        
        if (fila >= 0) {
            // 1. Obtener datos de la fila seleccionada
            // Columna 1: Nombre del Lector
            // Columna 2: Fecha Generada
            // Columna 3: Monto
            
            String lector = tblMultas.getValueAt(fila, 1).toString();
            String fecha = tblMultas.getValueAt(fila, 2).toString();
            String monto = tblMultas.getValueAt(fila, 3).toString();

            // 2. Mostrar en los campos de texto
            txtLector.setText(lector);
            txtFechaPrestamo.setText(fecha);

            // 3. Actualizar el lblTotal con el monto de la fila seleccionada
            lblTotal.setText(monto);
            
            // Opcional: Si quieres que el botón Pagar se habilite o cambie de texto, puedes hacerlo aquí
        }
    }//GEN-LAST:event_tblMultasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPrestamo;
    private javax.swing.JButton btnPagarMulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblMultas;
    private javax.swing.JTextField txtFechaPrestamo;
    private javax.swing.JTextField txtLector;
    // End of variables declaration//GEN-END:variables
}
