/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edgar Bernabe
 */
public class Multa extends javax.swing.JPanel {

    capaLogica.Multa objMulta = new capaLogica.Multa();
    DefaultTableModel modelo;
    int idPrestamoActual = -1;
    int idUsuarioActual = -1;

    /**
     * Creates new form Multa
     */
    public Multa() {
        initComponents();
        configurarTabla();
        lblTotal.setText("0.00");
    }

    private void configurarTabla() {
        modelo = new DefaultTableModel();
        modelo.addColumn("Nro Ejemplar"); // Viene de DETALLE_DEVOLUCION -> EJEMPLAR
        modelo.addColumn("Multa");        // Viene de DETALLE_DEVOLUCION
        modelo.addColumn("Observación");  // Viene de DETALLE_DEVOLUCION
        modelo.addColumn("Lector");       // Viene de USUARIO
        tblMultas.setModel(modelo);
    }

    // Método auxiliar
    private void limpiarFormulario() {
        modelo.setRowCount(0);
        lblTotal.setText("0.00");
        txtLector.setText("");
        txtFechaPrestamo.setDate(null);
        idPrestamoActual = -1;
        idUsuarioActual = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLector = new javax.swing.JTextField();
        btnBuscarPrestamo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMultas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnPagarMulta = new javax.swing.JButton();
        txtFechaPrestamo = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Fecha de Prestamo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Lector:");

        btnBuscarPrestamo.setBackground(new java.awt.Color(24, 118, 210));
        btnBuscarPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPrestamo.setText("Buscar Multas");
        btnBuscarPrestamo.setBorder(null);
        btnBuscarPrestamo.setBorderPainted(false);
        btnBuscarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestamoActionPerformed(evt);
            }
        });

        tblMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMultas);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("TOTAL:");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal.setText("0.0");

        btnPagarMulta.setBackground(new java.awt.Color(24, 118, 210));
        btnPagarMulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPagarMulta.setForeground(new java.awt.Color(255, 255, 255));
        btnPagarMulta.setText("PAGAR MULTA");
        btnPagarMulta.setBorder(null);
        btnPagarMulta.setBorderPainted(false);
        btnPagarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarMultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtLector, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal)
                                .addGap(427, 427, 427)
                                .addComponent(btnPagarMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(btnBuscarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(txtLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTotal)
                    .addComponent(btnPagarMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarMultaActionPerformed
        // Validaciones iniciales
        if (idPrestamoActual == -1 || idUsuarioActual == -1 || modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe buscar primero una multa pendiente.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Parsear y validar monto
        double total;
        try {
            String totalText = lblTotal.getText().trim().replace(",", ".");
            total = Double.parseDouble(totalText);

            if (total <= 0) {
                JOptionPane.showMessageDialog(this,
                        "El monto total debe ser mayor a 0.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al leer el monto total.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirmación
        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Confirma el pago de S/ " + String.format("%.2f", total) + "?\n"
                + "El lector será habilitado nuevamente.",
                "Confirmar Pago",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // Ejecutar pago
                objMulta.pagarMulta(idPrestamoActual, idUsuarioActual, total);

                // Mensaje de éxito
                JOptionPane.showMessageDialog(this,
                        "¡Pago registrado exitosamente!\n"
                        + "El lector ha sido habilitado.",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);

                // Limpiar formulario
                limpiarFormulario();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error al procesar el pago:\n" + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnPagarMultaActionPerformed

    private void btnBuscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamoActionPerformed
        if (txtFechaPrestamo.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione la fecha del préstamo.");
            return;
        }
        String lector = txtLector.getText().trim();
        if (lector.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del lector.");
            return;
        }

        try {
            java.sql.Date fechaSql = new java.sql.Date(txtFechaPrestamo.getDate().getTime());
            ResultSet rs = objMulta.buscarDetallesDeuda(fechaSql, lector);

            modelo.setRowCount(0);
            double sumaTotal = 0.0;
            idPrestamoActual = -1;
            idUsuarioActual = -1;

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("NroEjemplar"),
                    rs.getDouble("multa"),
                    rs.getString("observaciones"),
                    rs.getString("nombre_completo")
                });

                sumaTotal += rs.getDouble("multa");
                idPrestamoActual = rs.getInt("idprestamo");
                idUsuarioActual = rs.getInt("idusuario");
            }

            lblTotal.setText(String.format("%.2f", sumaTotal));

            // **AGREGAR ESTA VALIDACIÓN**:
            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Este lector no tiene multas pendientes o ya fueron pagadas.",
                        "Sin multas", JOptionPane.INFORMATION_MESSAGE);
                idPrestamoActual = -1; // Resetear
                idUsuarioActual = -1;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarPrestamoActionPerformed

    private void tblMultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMultasMouseClicked

    }//GEN-LAST:event_tblMultasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPrestamo;
    private javax.swing.JButton btnPagarMulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblMultas;
    private com.toedter.calendar.JDateChooser txtFechaPrestamo;
    private javax.swing.JTextField txtLector;
    // End of variables declaration//GEN-END:variables
}
