/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewsBibliotecario;

import capaLogica.Reportes;
import java.awt.BorderLayout;
import java.awt.Container;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Tocto Portocarrero Rodrigo Jesús
 */
public class Reporte15 extends javax.swing.JPanel {

    /**
     * Creates new form Reporte15
     */
    public Reporte15() {
        initComponents();
        Mostrar();
    }

    private void Mostrar() {
        try {

            // Pedir el año por JOptionPane
            String inputAnio = JOptionPane.showInputDialog(
                    this,
                    "Ingrese el AÑO del reporte (formato: YYYY)",
                    "Ingresar Año",
                    JOptionPane.QUESTION_MESSAGE
            );

            // Validar cancelación o vacío
            if (inputAnio == null || inputAnio.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Debe ingresar un año válido.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Validar que sea número
            if (!inputAnio.matches("\\d+")) {
                JOptionPane.showMessageDialog(this,
                        "El año debe contener solo números.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Validar longitud correcta
            if (inputAnio.length() != 4) {
                JOptionPane.showMessageDialog(this,
                        "El año debe tener 4 dígitos (ejemplo: 2024).",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Enviar parámetro al reporte
            Map<String, Object> parametros = new HashMap<>();
            parametros.put("anio", inputAnio);

            // Mostrar el reporte en el contenedor
            Container cont = this.contenedor;
            cont.setLayout(new BorderLayout());
            cont.removeAll();

            JRViewer viewer = new Reportes().reporteInterno("rp15tocto.jasper", parametros);

            cont.add(viewer);
            cont.revalidate();
            cont.repaint();
            viewer.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al generar el reporte: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JDesktopPane();

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane contenedor;
    // End of variables declaration//GEN-END:variables
}
