/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPrincipal;

import java.awt.BorderLayout;
import java.awt.Image;
import java.time.LocalDate;
import java.util.Locale;
import javax.swing.ImageIcon;
import viewsBibliotecario.ManAutor;
import viewsBibliotecario.ManCategoria;
import viewsBibliotecario.ManEditorial;
import viewsBibliotecario.ManLibro;
import viewsBibliotecario.PrincipalBibliotecario;
import viewsUsuario.PrestamosUsuario;
import viewsUsuario.PrincipalUsuario;

/**
 *
 * @author Tocto Portocarrero Rodrigo
 */
public class frmPrincipalBibliotecario extends javax.swing.JFrame {

    private String nombreUsuario;

    // Constructor con el nombre del usuario
    public frmPrincipalBibliotecario(String nombreUsuario) {
        initComponents();
        this.nombreUsuario = nombreUsuario.toUpperCase();
        SetDate();
        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(750, 430));
        content.setLayout(new java.awt.BorderLayout());
        InitContent();
        // Mostrar el nombre del usuario en el label
        lblNombreUsuarioPrincipal.setText(nombreUsuario);
        this.setResizable(false);
        this.setTitle("Sistema de Biblioteca-Panel de Bibliotecario");
        try {
            // 1. Carga la imagen como un recurso del proyecto (ruta relativa)
            Image icon = new ImageIcon(getClass().getResource("/Recursos/logo.png")).getImage();
            
            // 2. Establece la imagen como el icono de la ventana
            this.setIconImage(icon);
            
        } catch (Exception e) {
            System.err.println("Error al cargar el icono: " + e.getMessage());
            // Manejo básico de error si no se encuentra la imagen
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnPrincipalUsuario = new javax.swing.JButton();
        btnPrestamosUsuario = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGestionarlibro = new javax.swing.JButton();
        btnGestionareditorial = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombreUsuarioPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/logo.png")).getImage());

        background.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(0, 102, 255));
        menu.setPreferredSize(new java.awt.Dimension(270, 430));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BIBLIOTECA USAT");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logousat.jpg"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnPrincipalUsuario.setBackground(new java.awt.Color(0, 102, 255));
        btnPrincipalUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrincipalUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipalUsuario.setText("PRINCIPAL");
        btnPrincipalUsuario.setBorder(null);
        btnPrincipalUsuario.setBorderPainted(false);
        btnPrincipalUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPrincipalUsuario.setFocusPainted(false);
        btnPrincipalUsuario.setIconTextGap(10);
        btnPrincipalUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalUsuarioActionPerformed(evt);
            }
        });

        btnPrestamosUsuario.setBackground(new java.awt.Color(0, 102, 255));
        btnPrestamosUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrestamosUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestamosUsuario.setText("PRESTAMOS");
        btnPrestamosUsuario.setBorder(null);
        btnPrestamosUsuario.setBorderPainted(false);
        btnPrestamosUsuario.setFocusPainted(false);
        btnPrestamosUsuario.setIconTextGap(10);
        btnPrestamosUsuario.setMaximumSize(new java.awt.Dimension(108, 32));
        btnPrestamosUsuario.setMinimumSize(new java.awt.Dimension(108, 32));
        btnPrestamosUsuario.setPreferredSize(new java.awt.Dimension(108, 32));
        btnPrestamosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosUsuarioActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGestionarlibro.setBackground(new java.awt.Color(0, 102, 255));
        btnGestionarlibro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGestionarlibro.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarlibro.setText("GESTIONAR LIBRO");
        btnGestionarlibro.setBorder(null);
        btnGestionarlibro.setBorderPainted(false);
        btnGestionarlibro.setFocusPainted(false);
        btnGestionarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarlibroActionPerformed(evt);
            }
        });

        btnGestionareditorial.setBackground(new java.awt.Color(0, 102, 255));
        btnGestionareditorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGestionareditorial.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionareditorial.setText("  GESTIONAR EDITORIAL");
        btnGestionareditorial.setBorder(null);
        btnGestionareditorial.setBorderPainted(false);
        btnGestionareditorial.setFocusPainted(false);
        btnGestionareditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionareditorialActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GESTIONAR AUTOR");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GESTIONAR CATEGORIA");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPrincipalUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPrestamosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionarlibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionareditorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel5)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrincipalUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrestamosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionarlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionareditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        header.setBackground(new java.awt.Color(0, 153, 255));
        header.setPreferredSize(new java.awt.Dimension(750, 150));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Panel para el Bibliotecario");

        dateText.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("Hoy es {dayname} {day}  de {month} de {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(dateText)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(750, 430));
        content.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("SISTEMA DE BIBLIOTECA-BIBLIOTECARIO");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("BIENVENIDO");

        lblNombreUsuarioPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreUsuarioPrincipal.setText("???");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombreUsuarioPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(lblNombreUsuarioPrincipal))
                .addGap(29, 29, 29)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipalUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalUsuarioActionPerformed
        InitContent();

    }//GEN-LAST:event_btnPrincipalUsuarioActionPerformed

    private void btnPrestamosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosUsuarioActionPerformed
        PrestamosUsuario pres = new PrestamosUsuario();
        pres.setSize(750, 430);
        pres.setLocation(0, 0);

        content.removeAll();
        content.add(pres, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnPrestamosUsuarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Agregado por Valentino 
        // 1. Definir las opciones en español
        Object[] opciones = {"Sí", "No"};

        // 2. Mostrar el cuadro de diálogo de confirmación
        int resultado = javax.swing.JOptionPane.showOptionDialog(
                this, // Componente padre (el JFrame o JDialog actual)
                "¿De verdad quieres salir del panel del bibliotecario?", // Mensaje
                "Confirmar Salida", // Título de la ventana
                javax.swing.JOptionPane.YES_NO_OPTION, // Tipo de opciones
                javax.swing.JOptionPane.QUESTION_MESSAGE, // Tipo de icono
                null, // Sin icono personalizado
                opciones, // Opciones personalizadas: "Sí", "No"
                opciones[1] // Opción por defecto: "No"
        );

        // 3. Evaluar la respuesta
        if (resultado == javax.swing.JOptionPane.YES_OPTION) {
            // Si el usuario elige 'Sí', cierra la aplicación.
            frmInicioSesion obj = new frmInicioSesion();
            this.dispose();
            obj.setVisible(true);
            obj.setLocationRelativeTo(null);
            
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGestionarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarlibroActionPerformed
        ManLibro pres = new ManLibro();
        pres.setSize(750, 430);
        pres.setLocation(0, 0);

        content.removeAll();
        content.add(pres, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnGestionarlibroActionPerformed

    private void btnGestionareditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionareditorialActionPerformed
        //Realizado por Valentino
        ManEditorial pres = new ManEditorial();
        pres.setSize(750, 430);
        pres.setLocation(0, 0);

        content.removeAll();
        content.add(pres, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnGestionareditorialActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManAutor pres = new ManAutor();
        pres.setSize(750, 430);
        pres.setLocation(0, 0);

        content.removeAll();
        content.add(pres, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ManCategoria cat = new ManCategoria();
        cat.setSize(750, 430);
        cat.setLocation(0, 0);

        content.removeAll();
        content.add(cat, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void InitContent() {
        PrincipalBibliotecario pbl = new PrincipalBibliotecario();
        pbl.setSize(750, 430);
        pbl.setLocation(0, 0);

        content.removeAll();
        content.add(pbl, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }

    private void SetDate() {
        LocalDate now = LocalDate.now();

        int year = now.getYear();

        int dia = now.getDayOfMonth();

        int month = now.getMonthValue();

        String[] meses = {
            "Enero",
            "Febrero",
            "Marzo",
            "Abril",
            "Mayo",
            "Junio",
            "Julio",
            "Agosto",
            "Septiembre",
            "Octubre",
            "Noviembre",
            "Diciembre"
        };

        dateText.setText("Hoy es " + dia + " de " + meses[month - 1] + " de " + year);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnGestionareditorial;
    private javax.swing.JButton btnGestionarlibro;
    private javax.swing.JButton btnPrestamosUsuario;
    private javax.swing.JButton btnPrincipalUsuario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNombreUsuarioPrincipal;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
