/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPrincipal;

import java.awt.BorderLayout;
import java.awt.Image;
import java.time.LocalDate;
import java.util.Locale;
import javax.swing.ImageIcon;
import viewsBibliotecario.Devolucion;
import viewsBibliotecario.ManAutor;
import viewsBibliotecario.ManCategoria;
import viewsBibliotecario.ManEditorial;
import viewsBibliotecario.ManEjemplar;
import viewsBibliotecario.ManLibro;
import viewsBibliotecario.ManUsuarios;
import viewsBibliotecario.Multa;
import viewsBibliotecario.PrincipalBibliotecario;
import viewsUsuario.PrestamosUsuarios;

/**
 *
 * @author Tocto Portocarrero Rodrigo
 */
public class frmPrincipalBibliotecario extends javax.swing.JFrame {

    private String nombreUsuario;

    // Constructor con el nombre del usuario
    public frmPrincipalBibliotecario(String nombreUsuario) {
        initComponents();
        this.nombreUsuario = nombreUsuario.toUpperCase();
        SetDate();
        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(750, 430));
        content.setLayout(new java.awt.BorderLayout());
        InitContent();
        // Mostrar el nombre del usuario en el label
        lblNombreUsuarioPrincipal.setText(nombreUsuario);
        this.setResizable(false);
        this.setTitle("Sistema de Biblioteca-Panel de Bibliotecario");

        PrincipalBibliotecario eje = new PrincipalBibliotecario();
        eje.setSize(745, 430);
        eje.setLocation(0, 0);

        content.removeAll();
        content.add(eje, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        if (nombreUsuario.equals("ana.bibliotecaria")) {
            btnGestionarUsuarios.setEnabled(true);
        } else {
            btnGestionarUsuarios.setEnabled(false);
        }

        try {
            // 1. Carga la imagen como un recurso del proyecto (ruta relativa)
            Image icon = new ImageIcon(getClass().getResource("/Recursos/logo.png")).getImage();

            // 2. Establece la imagen como el icono de la ventana
            this.setIconImage(icon);

        } catch (Exception e) {
            System.err.println("Error al cargar el icono: " + e.getMessage());
            // Manejo básico de error si no se encuentra la imagen
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnEjemplar = new javax.swing.JButton();
        btnPrestamosUsuario = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGestionarlibro = new javax.swing.JButton();
        btnGestionareditorial = new javax.swing.JButton();
        btnGestionarAutor = new javax.swing.JButton();
        btnGestionarCategoria = new javax.swing.JButton();
        btnGestionarUsuarios = new javax.swing.JButton();
        btnDevolucion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombreUsuarioPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/logo.png")).getImage());

        background.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(0, 102, 255));
        menu.setPreferredSize(new java.awt.Dimension(270, 430));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BIBLIOTECA USAT");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logousat.jpg"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnEjemplar.setBackground(new java.awt.Color(0, 102, 255));
        btnEjemplar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEjemplar.setForeground(new java.awt.Color(255, 255, 255));
        btnEjemplar.setText("GESTIONAR EJEMPLAR");
        btnEjemplar.setBorder(null);
        btnEjemplar.setBorderPainted(false);
        btnEjemplar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEjemplar.setFocusPainted(false);
        btnEjemplar.setIconTextGap(10);
        btnEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjemplarActionPerformed(evt);
            }
        });

        btnPrestamosUsuario.setBackground(new java.awt.Color(0, 102, 255));
        btnPrestamosUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrestamosUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestamosUsuario.setText("PRESTAMOS");
        btnPrestamosUsuario.setBorder(null);
        btnPrestamosUsuario.setBorderPainted(false);
        btnPrestamosUsuario.setFocusPainted(false);
        btnPrestamosUsuario.setIconTextGap(10);
        btnPrestamosUsuario.setMaximumSize(new java.awt.Dimension(108, 32));
        btnPrestamosUsuario.setMinimumSize(new java.awt.Dimension(108, 32));
        btnPrestamosUsuario.setPreferredSize(new java.awt.Dimension(108, 32));
        btnPrestamosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosUsuarioActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGestionarlibro.setBackground(new java.awt.Color(0, 102, 255));
        btnGestionarlibro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGestionarlibro.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarlibro.setText("GESTIONAR LIBRO");
        btnGestionarlibro.setBorder(null);
        btnGestionarlibro.setBorderPainted(false);
        btnGestionarlibro.setFocusPainted(false);
        btnGestionarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarlibroActionPerformed(evt);
            }
        });

        btnGestionareditorial.setBackground(new java.awt.Color(0, 102, 255));
        btnGestionareditorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGestionareditorial.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionareditorial.setText("  GESTIONAR EDITORIAL");
        btnGestionareditorial.setBorder(null);
        btnGestionareditorial.setBorderPainted(false);
        btnGestionareditorial.setFocusPainted(false);
        btnGestionareditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionareditorialActionPerformed(evt);
            }
        });

        btnGestionarAutor.setBackground(new java.awt.Color(0, 102, 255));
        btnGestionarAutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGestionarAutor.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarAutor.setText("GESTIONAR AUTOR");
        btnGestionarAutor.setBorder(null);
        btnGestionarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarAutorActionPerformed(evt);
            }
        });

        btnGestionarCategoria.setBackground(new java.awt.Color(0, 102, 255));
        btnGestionarCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGestionarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarCategoria.setText("GESTIONAR CATEGORIA");
        btnGestionarCategoria.setBorder(null);
        btnGestionarCategoria.setBorderPainted(false);
        btnGestionarCategoria.setFocusPainted(false);
        btnGestionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarCategoriaActionPerformed(evt);
            }
        });

        btnGestionarUsuarios.setBackground(new java.awt.Color(0, 102, 255));
        btnGestionarUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGestionarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarUsuarios.setText("GESTIONAR USUARIOS");
        btnGestionarUsuarios.setBorder(null);
        btnGestionarUsuarios.setBorderPainted(false);
        btnGestionarUsuarios.setFocusPainted(false);
        btnGestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarUsuariosActionPerformed(evt);
            }
        });

        btnDevolucion.setBackground(new java.awt.Color(0, 102, 255));
        btnDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnDevolucion.setText("DEVOLUCIONES");
        btnDevolucion.setBorder(null);
        btnDevolucion.setBorderPainted(false);
        btnDevolucion.setFocusPainted(false);
        btnDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("MULTAS");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGestionareditorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionarCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionarAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEjemplar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGestionarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel3))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel5)))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(btnPrestamosUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGestionarlibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(btnDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrestamosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionarlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionareditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        header.setBackground(new java.awt.Color(0, 153, 255));
        header.setPreferredSize(new java.awt.Dimension(750, 150));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Panel para el Bibliotecario");

        dateText.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("Hoy es {dayname} {day}  de {month} de {year}");

        lblMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setText("????");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(141, 141, 141)
                        .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(dateText)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(750, 430));
        content.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("SISTEMA DE BIBLIOTECA-BIBLIOTECARIO");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("BIENVENIDO");

        lblNombreUsuarioPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreUsuarioPrincipal.setText("???");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombreUsuarioPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(lblNombreUsuarioPrincipal))
                .addGap(45, 45, 45)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjemplarActionPerformed
        ManEjemplar eje = new ManEjemplar();
        eje.setSize(750, 430);
        eje.setLocation(0, 0);

        content.removeAll();
        content.add(eje, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        lblMenu.setText("Gestionar Ejemplar");

    }//GEN-LAST:event_btnEjemplarActionPerformed

    private void btnPrestamosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosUsuarioActionPerformed
        PrestamosUsuarios pres = new PrestamosUsuarios();
        pres.setSize(750, 430);
        pres.setLocation(0, 0);

        content.removeAll();
        content.add(pres, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        lblMenu.setText("Prestamos");
    }//GEN-LAST:event_btnPrestamosUsuarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Agregado por Valentino 
        // 1. Definir las opciones en español
        Object[] opciones = {"Sí", "No"};

        // 2. Mostrar el cuadro de diálogo de confirmación
        int resultado = javax.swing.JOptionPane.showOptionDialog(
                this, // Componente padre (el JFrame o JDialog actual)
                "¿De verdad quieres salir del panel del bibliotecario?", // Mensaje
                "Confirmar Salida", // Título de la ventana
                javax.swing.JOptionPane.YES_NO_OPTION, // Tipo de opciones
                javax.swing.JOptionPane.QUESTION_MESSAGE, // Tipo de icono
                null, // Sin icono personalizado
                opciones, // Opciones personalizadas: "Sí", "No"
                opciones[1] // Opción por defecto: "No"
        );

        // 3. Evaluar la respuesta
        if (resultado == javax.swing.JOptionPane.YES_OPTION) {
            // Si el usuario elige 'Sí', cierra la aplicación.
            frmInicioSesion obj = new frmInicioSesion();
            this.dispose();
            obj.setVisible(true);
            obj.setLocationRelativeTo(null);

        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGestionarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarlibroActionPerformed
        ManLibro pres = new ManLibro();
        pres.setSize(750, 430);
        pres.setLocation(0, 0);

        content.removeAll();
        content.add(pres, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        lblMenu.setText("Gestionar Libro");
    }//GEN-LAST:event_btnGestionarlibroActionPerformed

    private void btnGestionareditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionareditorialActionPerformed
        //Realizado por Valentino
        ManEditorial pres = new ManEditorial();
        pres.setSize(750, 430);
        pres.setLocation(0, 0);

        content.removeAll();
        content.add(pres, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        lblMenu.setText("Gestionar Editorial");
    }//GEN-LAST:event_btnGestionareditorialActionPerformed

    private void btnGestionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarAutorActionPerformed
        ManAutor pres = new ManAutor();
        pres.setSize(750, 430);
        pres.setLocation(0, 0);

        content.removeAll();
        content.add(pres, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        lblMenu.setText("Gestionar Autor");
    }//GEN-LAST:event_btnGestionarAutorActionPerformed

    private void btnGestionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCategoriaActionPerformed
        ManCategoria cat = new ManCategoria();
        cat.setSize(750, 430);
        cat.setLocation(0, 0);

        content.removeAll();
        content.add(cat, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        lblMenu.setText("Gestionar Categoria");
    }//GEN-LAST:event_btnGestionarCategoriaActionPerformed

    private void btnGestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuariosActionPerformed
        ManUsuarios usu = new ManUsuarios();
        usu.setSize(750, 430);
        usu.setLocation(0, 0);
        content.removeAll();
        content.add(usu, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        lblMenu.setText("Gestionar Usuarios");
    }//GEN-LAST:event_btnGestionarUsuariosActionPerformed

    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed
        // 1. Instanciamos el panel de Devoluciones del Bibliotecario
        Devolucion pnl = new Devolucion();

        pnl.setSize(750, 430);
        pnl.setLocation(0, 0);

        content.removeAll();
        content.add(pnl, java.awt.BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        lblMenu.setText("Devoluciones");
    }//GEN-LAST:event_btnDevolucionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Multa mul = new Multa();

        mul.setSize(750, 430);
        mul.setLocation(0, 0);

        content.removeAll();
        content.add(mul, java.awt.BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        lblMenu.setText("Devoluciones");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void InitContent() {

        PrestamosUsuarios pres = new PrestamosUsuarios();
        pres.setSize(750, 430);
        pres.setLocation(0, 0);

        content.removeAll();
        content.add(pres, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        lblMenu.setText("Prestamos");

    }

    private void SetDate() {
        LocalDate now = LocalDate.now();

        int year = now.getYear();

        int dia = now.getDayOfMonth();

        int month = now.getMonthValue();

        String[] meses = {
            "Enero",
            "Febrero",
            "Marzo",
            "Abril",
            "Mayo",
            "Junio",
            "Julio",
            "Agosto",
            "Septiembre",
            "Octubre",
            "Noviembre",
            "Diciembre"
        };

        dateText.setText("Hoy es " + dia + " de " + meses[month - 1] + " de " + year);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnEjemplar;
    private javax.swing.JButton btnGestionarAutor;
    private javax.swing.JButton btnGestionarCategoria;
    private javax.swing.JButton btnGestionarUsuarios;
    private javax.swing.JButton btnGestionareditorial;
    private javax.swing.JButton btnGestionarlibro;
    private javax.swing.JButton btnPrestamosUsuario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNombreUsuarioPrincipal;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
